<div id="content" class="content bg-base section">
    <div class="row">
        <header class="page-header col-md-10 col-md-offset-1">
            <h2 class="page-title full-page-title">
                <?= $this->game->getTitle() ?>
            </h2>
        </header>
        <article class="entry style-single style-single-full type-post col-md-10 col-md-offset-1">
            <figure class="entry-thumbnail">
                <img src="<?= $this->game->getCoverArt() ?>" data-src="<?= $this->game->getCoverArt() ?>" data-src-retina="<?= $this->game->getCoverArt() ?>" width="680" height="452" alt="">
                <noscript>
                    <img src="<?= $this->game->getCoverArt() ?>" alt="" width="680" height="452">
                </noscript>
            </figure>
            <div class="entry-meta indented">
                <span class="author">by <a href="blog.html">John Doe</a></span>
                <span class="entry-date"><a href="blog.html">on <time datetime="2013-07-04T23:26:34+00:00">September 20 2013</time></a></span>
                <span class="category">In <a href="blog.html">Social Media</a></span>
            </div>
            <div class="entry-content indented">
                <p class="lead">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                </p>
                <p>
                    Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui.
                </p>
                <blockquote class="pulled-left">
                    <p>Better to remain silent and be thought a fool than to speak out and remove all doubt, <small> Abraham Lincoln</small></p>
                </blockquote>
                <p>
                    At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.
                </p>
                <!--
                sample for adding full image
                <figure class="image image-full">
                    <img src="../img/placeholder.gif" data-src="http://placehold.it/680x452" data-src-retina="http://placehold.it/1024x680" width="680" height="452" alt="">
                    <noscript>
                        <img src="http://placehold.it/680x452" alt="">
                    </noscript>
                </figure> -->
                <div class="gallery bg-page flushed-left">
                    <!-- <h4 class="gallery-title">Gallery</h4> -->
                    <div class="row">
                        <div class="col-xs-3 col-sm-2">
                            <a href="http://placehold.it/460x460" title="Image 1" class="thumbnail" data-rel="prettyPhoto[gallery]">
                                <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                <img src="../img/placeholder.gif" data-src="http://placehold.it/80x80" data-src-retina="http://placehold.it/160x160" width="80" height="80" alt="">
                                <!--fallback for no javascript browsers-->
                                <noscript>
                                    <img src="http://placehold.it/80x80" alt="">
                                </noscript>
                            </a>
                        </div><!--/.col-xs-2.col-sm-2-->
                        <div class="col-xs-3 col-sm-2">
                            <a href="http://placehold.it/460x460" title="Image 2" class="thumbnail" data-rel="prettyPhoto[gallery]">
                                <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                <img src="../img/placeholder.gif" data-src="http://placehold.it/80x80" data-src-retina="http://placehold.it/160x160" width="80" height="80" alt="">
                                <!--fallback for no javascript browsers-->
                                <noscript>
                                    <img src="http://placehold.it/80x80" alt="">
                                </noscript>
                            </a>
                        </div><!--/.col-xs-2.col-sm-2-->
                        <div class="col-xs-3 col-sm-2">
                            <a href="http://placehold.it/460x460" title="Image 3" class="thumbnail" data-rel="prettyPhoto[gallery]">
                                <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                <img src="../img/placeholder.gif" data-src="http://placehold.it/80x80" data-src-retina="http://placehold.it/160x160" width="80" height="80" alt="">
                                <!--fallback for no javascript browsers-->
                                <noscript>
                                    <img src="http://placehold.it/80x80" alt="">
                                </noscript>
                            </a>
                        </div><!--/.col-xs-2.col-sm-2-->
                        <div class="col-xs-3 col-sm-2">
                            <a href="http://placehold.it/460x460" title="Image 4" class="thumbnail" data-rel="prettyPhoto[gallery]">
                                <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                <img src="../img/placeholder.gif" data-src="http://placehold.it/80x80" data-src-retina="http://placehold.it/160x160" width="80" height="80" alt="">
                                <!--fallback for no javascript browsers-->
                                <noscript>
                                    <img src="http://placehold.it/80x80" alt="">
                                </noscript>
                            </a>
                        </div><!--/.col-xs-2.col-sm-2-->
                        <div class="col-xs-3 col-sm-2">
                            <a href="http://placehold.it/460x460" title="Image 5" class="thumbnail" data-rel="prettyPhoto[gallery]">
                                <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                <img src="../img/placeholder.gif" data-src="http://placehold.it/80x80" data-src-retina="http://placehold.it/160x160" width="80" height="80" alt="">
                                <!--fallback for no javascript browsers-->
                                <noscript>
                                    <img src="http://placehold.it/80x80" alt="">
                                </noscript>
                            </a>
                        </div><!--/.col-xs-2.col-sm-2-->
                        <div class="col-xs-3 col-sm-2">
                            <a href="http://placehold.it/460x460" title="Image 6" class="thumbnail" data-rel="prettyPhoto[gallery]">
                                <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                <img src="../img/placeholder.gif" data-src="http://placehold.it/80x80" data-src-retina="http://placehold.it/160x160" width="80" height="80" alt="">
                                <!--fallback for no javascript browsers-->
                                <noscript>
                                    <img src="http://placehold.it/80x80" alt="">
                                </noscript>
                            </a>
                        </div><!--/.col-xs-2.col-sm-2-->
                        <div class="col-xs-3 col-sm-2">
                            <a href="http://placehold.it/460x460" title="Image 7" class="thumbnail" data-rel="prettyPhoto[gallery]">
                                <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                <img src="../img/placeholder.gif" data-src="http://placehold.it/80x80" data-src-retina="http://placehold.it/160x160" width="80" height="80" alt="">
                                <!--fallback for no javascript browsers-->
                                <noscript>
                                    <img src="http://placehold.it/80x80" alt="">
                                </noscript>
                            </a>
                        </div><!--/.col-xs-2.col-sm-2-->
                        <div class="col-xs-3 col-sm-2">
                            <a href="http://placehold.it/460x460" title="Image 8" class="thumbnail" data-rel="prettyPhoto[gallery]">
                                <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                <img src="../img/placeholder.gif" data-src="http://placehold.it/80x80" data-src-retina="http://placehold.it/160x160" width="80" height="80" alt="">
                                <!--fallback for no javascript browsers-->
                                <noscript>
                                    <img src="http://placehold.it/80x80" alt="">
                                </noscript>
                            </a>
                        </div><!--/.col-xs-2.col-sm-2-->
                        <div class="col-xs-3 col-sm-2">
                            <a href="http://placehold.it/460x460" title="Image 9" class="thumbnail" data-rel="prettyPhoto[gallery]">
                                <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                <img src="../img/placeholder.gif" data-src="http://placehold.it/80x80" data-src-retina="http://placehold.it/160x160" width="80" height="80" alt="">
                                <!--fallback for no javascript browsers-->
                                <noscript>
                                    <img src="http://placehold.it/80x80" alt="">
                                </noscript>
                            </a>
                        </div><!--/.col-xs-2.col-sm-2-->
                        <div class="col-xs-3 col-sm-2">
                            <a href="http://placehold.it/460x460" title="Image 10" class="thumbnail" data-rel="prettyPhoto[gallery]">
                                <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                <img src="../img/placeholder.gif" data-src="http://placehold.it/80x80" data-src-retina="http://placehold.it/160x160" width="80" height="80" alt="">
                                <!--fallback for no javascript browsers-->
                                <noscript>
                                    <img src="http://placehold.it/80x80" alt="">
                                </noscript>
                            </a>
                        </div><!--/.col-xs-2.col-sm-2-->
                        <div class="col-xs-3 col-sm-2">
                            <a href="http://placehold.it/460x460" title="Image 10" class="thumbnail" data-rel="prettyPhoto[gallery]">
                                <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                <img src="../img/placeholder.gif" data-src="http://placehold.it/80x80" data-src-retina="http://placehold.it/160x160" width="80" height="80" alt="">
                                <!--fallback for no javascript browsers-->
                                <noscript>
                                    <img src="http://placehold.it/80x80" alt="">
                                </noscript>
                            </a>
                        </div><!--/.col-xs-2.col-sm-2-->
                        <div class="col-xs-3 col-sm-2">
                            <a href="http://placehold.it/460x460" title="Image 2" class="thumbnail" data-rel="prettyPhoto[gallery]">
                                <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                <img src="../img/placeholder.gif" data-src="http://placehold.it/80x80" data-src-retina="http://placehold.it/160x160" width="80" height="80" alt="">
                                <!--fallback for no javascript browsers-->
                                <noscript>
                                    <img src="http://placehold.it/80x80" alt="">
                                </noscript>
                            </a>
                        </div><!--/.col-xs-2.col-sm-2-->
                    </div><!--/.row-->
                </div><!--/.gallery-->
                <h3>Verdict</h3>
                <p>
                    At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.
                </p>
                <h3>Score</h3>
                <ul class="entries">
                    <li class="entry style-score-widget">
                        <div class="score-value">81</div>
                        <div class="score-label entry-title"><a href="single-full.html">Design</a></div>
                        <div class="progress">
                            <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 81%;">
                            </div>
                        </div>
                    </li>
                    <li class="entry style-score-widget">
                        <div class="score-value">80</div>
                        <div class="score-label entry-title"><a href="single-full.html">Functionality</a></div>
                        <div class="progress">
                            <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 80%;">
                            </div>
                        </div>
                    </li>
                    <li class="entry style-score-widget">
                        <div class="score-value">76</div>
                        <div class="score-label entry-title"><a href="single-full.html">Performance</a></div>
                        <div class="progress">
                            <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 75%;">
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </article>
        <div class="col-md-10 col-md-offset-1">
            <div class="after-entry indented">
                <hr>
                <aside class="widget">
                    <i class="icon-tags"></i> Tags:
                    <a href="#"> Some</a>
                    <a href="#"> Goes</a>
                    <a href="#"> Here</a>
                    <a href="#"> For</a>
                    <a href="#"> Sure</a>
                </aside>
                <hr>
                <aside class="widget widget-author media">
                    <figure class="entry-author-avatar media-object avatar pull-left">
                        <!-- to disable lazy loading, remove data-src and data-src-retina -->
                        <img src="../img/placeholder.gif" data-src="http://placehold.it/230x230" data-src-retina="http://placehold.it/460x460" width="230" height="230" class="img-circle" alt="">
                        <!--fallback for no javascript browsers-->
                        <noscript>
                            <img src="http://placehold.it/230x230" alt="">
                        </noscript>
                    </figure>
                    <div class="media-body">
                        <h4 class="entry-author-name">By <a href="blog.html">John Doe</a></h4>
                        <p>
                            Deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.
                        </p>
                    </div>
                </aside>
                <hr>
                <aside class="widget">
                    <h4 class="widget-title">Related Posts</h4>
                    <div class="entries row">
                        <article class="entry type-post style-thumbnail col-xs-3 col-sm-3">
                            <figure class="entry-thumbnail">
                                <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                <img src="../img/placeholder.gif" data-src="http://placehold.it/230x230" data-src-retina="http://placehold.it/460x460" width="230" height="230" alt="">
                                <!--fallback for no javascript browsers-->
                                <noscript>
                                    <img src="http://placehold.it/230x230" alt="">
                                </noscript>
                            </figure>
                            <h3 class="entry-title"><a href="single.html">Sed ut perspiciatis unde omnis.</a> </h3>

                        </article>
                        <article class="entry type-post style-thumbnail col-xs-3 col-sm-3">
                            <figure class="entry-thumbnail">
                                <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                <img src="../img/placeholder.gif" data-src="http://placehold.it/230x230" data-src-retina="http://placehold.it/460x460" width="230" height="230" alt="">
                                <!--fallback for no javascript browsers-->
                                <noscript>
                                    <img src="http://placehold.it/230x230" alt="">
                                </noscript>
                            </figure>
                            <h3 class="entry-title"><a href="single.html">Oomnis iste natus error sit voluptatem.</a> </h3>

                        </article>
                        <article class="entry type-post style-thumbnail col-xs-3 col-sm-3">
                            <figure class="entry-thumbnail">
                                <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                <img src="../img/placeholder.gif" data-src="http://placehold.it/230x230" data-src-retina="http://placehold.it/460x460" width="230" height="230" alt="">
                                <!--fallback for no javascript browsers-->
                                <noscript>
                                    <img src="http://placehold.it/230x230" alt="">
                                </noscript>
                            </figure>
                            <h3 class="entry-title"><a href="single.html">Temporibus autem quibusdam.</a> </h3>
                        </article>
                        <article class="entry type-post style-thumbnail col-xs-3 col-sm-3">
                            <figure class="entry-thumbnail">
                                <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                <img src="../img/placeholder.gif" data-src="http://placehold.it/230x230" data-src-retina="http://placehold.it/460x460" width="230" height="230" alt="">
                                <!--fallback for no javascript browsers-->
                                <noscript>
                                    <img src="http://placehold.it/230x230" alt="">
                                </noscript>
                            </figure>
                            <h3 class="entry-title"><a href="single.html">Siste natus error sit voluptatem.</a> </h3>

                        </article>
                    </div>
                </aside>
                <hr>
                <aside class="widget">
                    Share:
                    <a href="#" class="" onclick="window.open(
                        'https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(location.href),
                        'facebook-share-dialog',
                        'width=626,height=436');
                        return false;"><span class="icon-stack"><i class="icon-sign-blank icon-stack-base"></i><i class="icon-facebook icon-light"></i></span></a>
                    <a href="#" class="" onclick="window.open(
                        'http://twitter.com/home?status='+encodeURIComponent(location.href),
                        'facebook-share-dialog',
                        'width=626,height=436');
                        return false;"><span class="icon-stack"><i class="icon-sign-blank icon-stack-base"></i><i class="icon-twitter icon-light"></i></span></a>
                    <a href="#" class="" onclick="window.open(
                        'https://plus.google.com/share?url='+encodeURIComponent(location.href),
                        'facebook-share-dialog',
                        'width=500,height=436');
                        return false;"><span class="icon-stack"><i class="icon-sign-blank icon-stack-base"></i><i class="icon-google-plus icon-light"></i></span></a>
                    <a href="#" class="" onclick="javascript:void((function(){var e=document.createElement('script');e.setAttribute('type','text/javascript');e.setAttribute('charset','UTF-8');e.setAttribute('src','http://assets.pinterest.com/js/pinmarklet.js?r='+Math.random()*99999999);document.body.appendChild(e)})());"><span class="icon-stack"><i class="icon-sign-blank icon-stack-base"></i><i class="icon-pinterest icon-light"></i></span></a>
                </aside>
            </div>
            <div id="comments" class="comments-area indented">
                <h4 class="comments-title">Comments</h4>
                <ol class="media-list comment-list">
                    <li class="media comment">
                        <img src="http://0.gravatar.com/avatar/ad516503a11cd5ca435acc9bb6523536?s=74" width="74" height="74" alt="" class="avatar media-object pull-left img-circle">
                        <div class="media-body">
                            <h4 class="media-heading author-vcard">
                                <cite class="fn"><a href="#" rel="external nofollow" class="url">Mr John Doe</a></cite>
                                <span class="comment-meta commentmetadata">on <a href="#">July 8, 2013 at 7:46 am</a></span>
                            </h4>
                            <p>Hi, this is a comment. enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur.</p>
                        </div>
                        <ol class="media-list">
                            <li class="media comment">
                                <img src="http://0.gravatar.com/avatar/ad516503a11cd5ca435acc9bb6523536?s=74" width="74" height="74" alt="" class="avatar media-object pull-left img-circle">
                                <div class="media-body">
                                    <h4 class="media-heading author-vcard">
                                        <cite class="fn"><a href="#" rel="external nofollow" class="url">Mr John Doe</a></cite>
                                        <span class="comment-meta commentmetadata"> on <a href="#">July 8, 2013 at 7:46 am</a></span>
                                    </h4>
                                    <p>Hi, this is a comment. enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur.</p>
                                </div>
                            </li>
                            <li class="media comment">
                                <img src="http://0.gravatar.com/avatar/ad516503a11cd5ca435acc9bb6523536?s=74" width="74" height="74" alt="" class="avatar media-object pull-left img-circle">
                                <div class="media-body">
                                    <h4 class="media-heading author-vcard">
                                        <cite class="fn"><a href="#" rel="external nofollow" class="url">Mr John Doe</a></cite>
                                        <span class="comment-meta commentmetadata"> on <a href="#">July 8, 2013 at 7:46 am</a></span>
                                    </h4>
                                    <p>Hi, this is a comment. enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur.</p>
                                </div>
                                <ol class="media-list">
                                    <li class="media comment">
                                        <img src="http://0.gravatar.com/avatar/ad516503a11cd5ca435acc9bb6523536?s=74" width="74" height="74" alt="" class="avatar media-object pull-left img-circle">
                                        <div class="media-body">
                                            <h4 class="media-heading author-vcard">
                                                <cite class="fn"><a href="#" rel="external nofollow" class="url">Mr John Doe</a></cite>
                                                <span class="comment-meta commentmetadata">on <a href="#">July 8, 2013 at 7:46 am</a></span>
                                            </h4>
                                            <p>Hi, this is a comment. enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur.</p>
                                        </div>
                                    </li>
                                    <li class="media comment">
                                        <img src="http://0.gravatar.com/avatar/ad516503a11cd5ca435acc9bb6523536?s=74" width="74" height="74" alt="" class="avatar media-object pull-left img-circle">
                                        <div class="media-body">
                                            <h4 class="media-heading author-vcard">
                                                <cite class="fn"><a href="#" rel="external nofollow" class="url">Mr John Doe</a></cite>
                                                <span class="comment-meta commentmetadata">on <a href="#">July 8, 2013 at 7:46 am</a></span>
                                            </h4>
                                            <p>Hi, this is a comment. enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur.</p>
                                        </div>
                                    </li>
                                </ol>
                            </li>
                        </ol>
                    </li>
                    <li class="media comment">
                        <img src="http://0.gravatar.com/avatar/ad516503a11cd5ca435acc9bb6523536?s=74" width="74" height="74" alt="" class="avatar media-object pull-left img-circle">
                        <div class="media-body">
                            <h4 class="media-heading author-vcard">
                                <cite class="fn"><a href="#" rel="external nofollow" class="url">Mr John Doe</a></cite>
                                <span class="comment-meta commentmetadata">on <a href="#">July 8, 2013 at 7:46 am</a></span>
                            </h4>
                            <p>Hi, this is a comment. enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur.</p>
                        </div>
                    </li>
                    <li class="media comment">
                        <img src="http://0.gravatar.com/avatar/ad516503a11cd5ca435acc9bb6523536?s=74" width="74" height="74" alt="" class="avatar media-object pull-left img-circle">
                        <div class="media-body">
                            <h4 class="media-heading author-vcard">
                                <cite class="fn"><a href="#" rel="external nofollow" class="url">Mr John Doe</a></cite>
                                <span class="comment-meta commentmetadata">on <a href="#">July 8, 2013 at 7:46 am</a></span>
                            </h4>
                            <p>Hi, this is a comment. enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur.</p>
                        </div>
                    </li>
                </ol>
                <div id="respond" class="comments-respond">
                    <h3 id="reply-title" class="comment-reply-title">Leave a Reply</h3>
                    <form action="#" class="form-inline row" method="post" id="commentform">
                        <div class="form-group col-lg-4 col-md-4 col-sm-4 col-xs-12">
                            <label class="sr-only" for="inputName">Name</label>
                            <input class="form-control" id="inputName" name="author" type="text" value="" aria-required="true" placeholder="Your Name">
                        </div>
                        <div class="form-group col-lg-4 col-md-4 col-sm-4 col-xs-12">
                            <label class="sr-only" for="inputEmail">Email</label>
                            <input class="form-control" id="inputEmail" name="author" type="text" value="" aria-required="true" placeholder="Your Email">
                        </div>
                        <div class="form-group col-lg-4 col-md-4 col-sm-4 col-xs-12">
                            <label class="sr-only" for="inputWebsite">Website</label>
                            <input class="form-control" id="inputWebsite" name="author" type="text" value="" aria-required="true" placeholder="Your Website">
                        </div>
                        <div class="form-group col-lg-12 col-md-12 col-sm-12">
                            <label class="sr-only" for="inputMessage">Message</label>
                            <textarea class="form-control" id="inputMessage" name="message" rows="8" aria-required="true" placeholder="Your Message"></textarea>
                        </div>
                        <div class="form-group col-lg-12 col-md-12 col-sm-12">
                            <button class="btn btn-primary" name="submit" id="submit">Send Message</button>
                        </div>
                    </form>
                </div><!-- #respond -->
            </div><!--/#comments-->

        </div>
    </div><!--/.col-md-8.col-lg-8.col-xl-9-->
</div><!--/#content-->