<div class="col-4 col-sm-6 col-lg-12">
     <p><center><a class="btn btn-default" href="#" role="button">Upload hint book scans &raquo;</a></center></p>
</div>
<h2>Sierra Hint Books</h2>
<div class="well">
<div class="row">
     <div class="col-4 col-sm-6 col-lg-12">(Left-click to view, right-click to download)<br><br></div>
</div>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Adventures_of_Willy_Beamish_Hint_Book.pdf" target="_blank">Black Cauldron (The) Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Black_Cauldron_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Black_Cauldron_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Codename_Iceman_Hint_Book.pdf" target="_blank">Code Name: Iceman Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Codename_Iceman_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Codename_Iceman_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Conquest_1_Conquest_of_Camelot_Hint_Book.pdf" target="_blank">Conquests of Camelot Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Conquest_1_Conquest_of_Camelot_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Conquest_1_Conquest_of_Camelot_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Conquest_2_Conquest_of_the_Longbow_Hint_Book.pdf" target="_blank">Conquests of the Longbow Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Conquest_2_Conquest_of_the_Longbow_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Conquest_2_Conquest_of_the_Longbow_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Dr_Brain_1_Castle_of_Dr_Brain_1_Hint_Book.pdf" target="_blank">Castle of Dr. Brain Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Dr_Brain_1_Castle_of_Dr_Brain_1_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Dr_Brain_1_Castle_of_Dr_Brain_1_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/EcoQuest_1_Search_For_Cetus_Hint_Book.pdf" target="_blank">EcoQuest: The Search for Cetus Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/EcoQuest_1_Search_For_Cetus_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/EcoQuest_1_Search_For_Cetus_Hint_Book_cover.jpg"></a>
     </div>
</div>
<p></p>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/EcoQuest_2_Lost_Secret_of_the_Rainforest_Hint_Book.pdf" target="_blank">EcoQuest 2 Hint Book</a><br><br>
          <a href="/gfx/Publications/hintbooks/EcoQuest_2_Lost_Secret_of_the_Rainforest_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/EcoQuest_2_Lost_Secret_of_the_Rainforest_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Even_More_Incredible_Machine_Hint_Book.pdf" target="_blank">Even More Incredible Machine (The) Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Even_More_Incredible_Machine_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Even_More_Incredible_Machine_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Freddy_Pharkas_Hint_Book.pdf" target="_blank">Freddy Pharkas Frontier Pharmacist Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Freddy_Pharkas_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Freddy_Pharkas_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Gabriel_Knight_1_Hintbook.pdf" target="_blank">Gabriel Knight: Sins of the Fathers Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Gabriel_Knight_1_Hintbook.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Gabriel_Knight_1_Hintbook_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Goblins_1_Hint_Book.pdf" target="_blank">Gobliiins Hint Book</a><br><br>
          <a href="/gfx/Publications/hintbooks/Goblins_1_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Goblins_1_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Goblins_2_Hint_Book.pdf" target="_blank">Gobliins 2 Hint Book</a><br><br>
          <a href="/gfx/Publications/hintbooks/Goblins_2_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Goblins_2_Hint_Book_cover.jpg"></a>
     </div>
</div>
<p></p>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Goblins_3_Hint_Book.pdf" target="_blank">Goblins Quest 3 Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Goblins_3_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Goblins_3_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Gold_Rush_Hint_Book.pdf" target="_blank">Gold Rush! Hint Book</a><br><br>
          <a href="/gfx/Publications/hintbooks/Gold_Rush_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Gold_Rush_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Gold_Rush_Hint_Book.pdf" target="_blank">Gold Rush! Hint Book</a><br><br>
          <a href="/gfx/Publications/hintbooks/Gold_Rush_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Gold_Rush_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Heart_of_China_Hint_Book.pdf" target="_blank">Heart of China Hint Book</a><br><br>
          <a href="/gfx/Publications/hintbooks/Heart_of_China_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Heart_of_China_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Inca_1_Hint_Book.pdf" target="_blank">Inca Hint Book</a><br><br>
          <a href="/gfx/Publications/hintbooks/Inca_1_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Inca_1_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Inca_2_Hint_Book.pdf" target="_blank">Inca 2 Hint Book</a><br><br>
          <a href="/gfx/Publications/hintbooks/Inca_2_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Inca_2_Hint_Book_cover.jpg"></a>
     </div>
</div>
<p></p>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Kings_Quest_1_Hint_Book.pdf" target="_blank">King's Quest 1 Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Kings_Quest_1_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Kings_Quest_1_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Kings_Quest_2_Hint_Book.pdf" target="_blank">King's Quest 2 Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Kings_Quest_2_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Kings_Quest_2_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Kings_Quest_3_Hint_Book.pdf" target="_blank">King's Quest 3 Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Kings_Quest_3_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Kings_Quest_3_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Kings_Quest_4_Hint_Book.pdf" target="_blank">King's Quest 4 Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Kings_Quest_4_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Kings_Quest_4_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Kings_Quest_5_Hint_Book.pdf" target="_blank">King's Quest 5 Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Kings_Quest_5_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Kings_Quest_5_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Kings_Quest_6_Hint_Book.pdf" target="_blank">King's Quest 6 Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Kings_Quest_6_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Kings_Quest_6_Hint_Book_cover.jpg"></a>
     </div>
</div>
<p></p>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Kings_Quest_7_Hint_Book.pdf" target="_blank">King's Quest 7 Hint Book</a><br><br>
          <a href="/gfx/Publications/hintbooks/Kings_Quest_7_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Kings_Quest_7_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Laura_Bow_1_Colonels_Bequest_Hint_Book.pdf" target="_blank">Laura Bow 1 Hint Book</a><br><br>
          <a href="/gfx/Publications/hintbooks/Laura_Bow_1_Colonels_Bequest_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Laura_Bow_1_Colonels_Bequest_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Laura_Bow_2_Dagger_Of_Amon_Ra_Hint_Book.pdf" target="_blank">Laura Bow 2 Hint Book</a><br><br>
          <a href="/gfx/Publications/hintbooks/Laura_Bow_2_Dagger_Of_Amon_Ra_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Laura_Bow_2_Dagger_Of_Amon_Ra_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Leisure_Suit_Larry_1_Hint_Book.pdf" target="_blank">Leisure Suit Larry 1 Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Leisure_Suit_Larry_1_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Leisure_Suit_Larry_1_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Leisure_Suit_Larry_2_Hint_Book.pdf" target="_blank">Leisure Suit Larry 2 Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Leisure_Suit_Larry_2_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Leisure_Suit_Larry_2_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Leisure_Suit_Larry_3_Hint_Book.pdf" target="_blank">Leisure Suit Larry 3 Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Leisure_Suit_Larry_3_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Leisure_Suit_Larry_3_Hint_Book_cover.jpg"></a>
     </div>
</div>
<p></p>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Leisure_Suit_Larry_5_Hint_Book.pdf" target="_blank">Leisure Suit Larry 5 Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Leisure_Suit_Larry_5_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Leisure_Suit_Larry_5_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Leisure_Suit_Larry_6_Hint_Book.pdf" target="_blank">Leisure Suit Larry 6 Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Leisure_Suit_Larry_6_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Leisure_Suit_Larry_6_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Lost_In_Time_Hint_Book.pdf" target="_blank">Lost in Time Hint Book</a><br><br>
          <a href="/gfx/Publications/hintbooks/Lost_In_Time_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Lost_In_Time_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Manhunter_1_New_Yotk_Hint_Book.pdf" target="_blank">Manhunter 1 Hint Book</a><br><br>
          <a href="/gfx/Publications/hintbooks/Manhunter_1_New_Yotk_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Manhunter_1_New_Yotk_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Manhunter_2_San_Francisco_Hint_Book.pdf" target="_blank">Manhunter 2 Hint Book</a><br><br>
          <a href="/gfx/Publications/hintbooks/Manhunter_2_San_Francisco_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Manhunter_2_San_Francisco_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Police_Quest_1_Hint_Book.pdf" target="_blank">Police Quest 1 Hint Book</a><br><br>
          <a href="/gfx/Publications/hintbooks/Police_Quest_1_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Police_Quest_1_Hint_Book_cover.jpg"></a>
     </div>
</div>
<p></p>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Police_Quest_2_Hint_Book.pdf" target="_blank">Police Quest 2 Hint Book</a><br><br>
          <a href="/gfx/Publications/hintbooks/Police_Quest_2_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Police_Quest_2_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Police_Quest_3_Hint_Book.pdf" target="_blank">Police Quest 3 Hint Book</a><br><br>
          <a href="/gfx/Publications/hintbooks/Police_Quest_3_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Police_Quest_3_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Police_Quest_4_Hint_Book.pdf" target="_blank">Police Quest 4 Hint Book</a><br><br>
          <a href="/gfx/Publications/hintbooks/Police_Quest_4_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Police_Quest_4_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Prophecy_Hint_Book.pdf" target="_blank">The Prophecy Hint Book</a><br><br>
          <a href="/gfx/Publications/hintbooks/Prophecy_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Prophecy_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Quest_for_Glory_1_Hint_Book.pdf" target="_blank">Quest for Glory 1 Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Quest_for_Glory_1_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Quest_for_Glory_1_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Quest_for_Glory_2_Hint_Book.pdf" target="_blank">Quest for Glory 2 Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Quest_for_Glory_2_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Quest_for_Glory_2_Hint_Book_cover.jpg"></a>
     </div>
</div>
<p></p>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Quest_for_Glory_3_Hint_Book.pdf" target="_blank">Quest for Glory 3 Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Quest_for_Glory_3_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Quest_for_Glory_3_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Quest_for_Glory_4_Hint_Book.pdf" target="_blank">Quest for Glory 4 Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Quest_for_Glory_4_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Quest_for_Glory_4_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Rise_of_the_Dragon_Hint_Book.pdf" target="_blank">Rise of the Dragon Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Rise_of_the_Dragon_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Rise_of_the_Dragon_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Space_Quest_1_Hint_Book.pdf" target="_blank">Space Quest 1 (VGA) Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Space_Quest_1_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Space_Quest_1_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Space_Quest_2_Hint_Book.pdf" target="_blank">Space Quest 2 Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Space_Quest_2_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Space_Quest_2_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Space_Quest_3_Hint_Book.pdf" target="_blank">Space Quest 3 Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Space_Quest_3_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Space_Quest_3_Hint_Book_cover.jpg"></a>
     </div>
</div>
<p></p>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Space_Quest_4_Hint_Book.pdf" target="_blank">Space Quest 4 Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Space_Quest_4_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Space_Quest_4_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Space_Quest_5_Hint_Book.pdf" target="_blank">Space Quest 5 Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Space_Quest_5_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Space_Quest_5_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Adventures_of_Willy_Beamish_Hint_Book.pdf" target="_blank">Willy Beamish (The Adventures of) Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Adventures_of_Willy_Beamish_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Adventures_of_Willy_Beamish_Hint_Book_cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="/gfx/Publications/hintbooks/Woodruff_and_the_Schnibble_Hint_Book.pdf" target="_blank">Woodruff and the Schnibble Hint Book</a><br>
          <a href="/gfx/Publications/hintbooks/Woodruff_and_the_Schnibble_Hint_Book.pdf" target="_blank"><img src="/gfx/Publications/hintbooks/Woodruff_and_the_Schnibble_Hint_Book_cover.jpg"></a>
     </div>
</div>
</div>

<h2>Series guide books</h2>
<div class="well">
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          The Official Book of King's Quest<br><br>
          <img src="/gfx/Publications/guides/Official_book_of_kings_quest_cover.jpg">
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          The Official Book of King's Quest: Second Edition<br>
          <img src="/gfx/Publications/guides/Official_book_of_kings_quest_2_cover.jpg">
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          The Official Book of King's Quest: Third Edition<br>
          <img src="/gfx/Publications/guides/Official_book_of_kings_quest_3_cover.jpg">
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          The King's Quest Companion<br><br>
          <img src="/gfx/Publications/guides/Kings_Quest_Companion.jpg">
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          The King's Quest Companion: Second Edition<br>
          <img src="/gfx/Publications/guides/Kings_Quest_Companion_2.jpg">
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          The King's Quest Companion: Third Edition<br>
          <img src="/gfx/Publications/guides/Kings_Quest_Companion_3.jpg">
     </div>
</div>
<p></p>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          The King's Quest Companion: Fourth Edition<br>
          <img src="/gfx/Publications/guides/Kings_Quest_Companion_4.jpg">
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          The Official Book of Leisure Suit Larry<br><br>
          <img src="/gfx/Publications/guides/official_book_of_lsl.jpg">
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          The Official Book of Leisure Suit Larry: Second Edition<br>
          <img src="/gfx/Publications/guides/official_book_of_lsl_2.jpg">
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          The Official Book of Leisure Suit Larry: Third Edition<br>
          <img src="/gfx/Publications/guides/official_book_of_lsl_3.jpg">
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          The Official Book of Leisure Suit Larry: Special Edition<br>
          <img src="/gfx/Publications/guides/official_book_of_lsl_se.jpg">
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          The Leisure Suit Larry Bedside Companion<br><br>
          <img src="/gfx/Publications/guides/lsl_bedside_companion.jpg">
     </div>
</div>
<p></p>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          The Leisure Suit Larry Bedside Companion: Second Edition<br>
          <img src="/gfx/Publications/guides/lsl_bedside_companion_2.jpg">
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          The Larry Story<br><br><br>
          <img src="/gfx/Publications/guides/larry_story.jpg">
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          The Official Book of Police Quest<br><br>
          <img src="/gfx/Publications/guides/official_book_of_pq.jpg">
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          The Police Quest Casebook<br><br>
          <img src="/gfx/Publications/guides/police_quest_casebook.jpg">
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          The Police Quest Casebook: Second Edition<br>
          <img src="/gfx/Publications/guides/police_quest_casebook_2.jpg">
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          Quest for Glory Strategy Guide<br><br>
          <img src="/gfx/Publications/guides/Quest_for_Glory.jpg">
     </div>

</div>
<p></p>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          The Official Guide to Roger Wilco Space Adventures<br>
          <img src="/gfx/Publications/guides/Roger_Wilco_Space_Adventures.jpg">
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          The Official Guide to Roger Wilco Space Adventures: 2nd Edition<br>
          <img src="/gfx/Publications/guides/Roger_Wilco_Space_Adventures_2.jpg">
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          The Space Quest Companion<br><br>
          <img src="/gfx/Publications/guides/Space_Quest_Companion.jpg">
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          The Space Quest Companion: 2nd Edition<br><br>
          <img src="/gfx/Publications/guides/Space_Quest_Companion_2.jpg">
     </div>

</div>
</div>
