<div class="col-4 col-sm-6 col-lg-12">
     <p><center><a class="btn btn-default" href="#" role="button">Upload Buyer's Guide scans &raquo;</a></center></p>
</div>
<h2>Buyer's Guides</h2>
<div class="well">
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Buyer's Guide - Spring 1996</a><br>
          <a href="#"><img src="/gfx/Publications/BG/1996_Spring/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Buyer's Guide - Summer 1996</a><br>
          <a href="#"><img src="/gfx/Publications/BG/1996_Summer/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Buyer's Guide - Fall 1996</a><br>
          <a href="#"><img src="/gfx/Publications/BG/1996_Fall/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Buyer's Guide - Summer 1997</a><br>
          <a href="#"><img src="/gfx/Publications/BG/1997_Summer/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Buyer's Guide - Winter 1997</a><br>
          <a href="#"><img src="/gfx/Publications/BG/1997_Winter/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Buyer's Guide - Spring 1998</a><br>
          <a href="#"><img src="/gfx/Publications/BG/1998_Spring/01.JPG"></a>
     </div>
</div>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Buyer's Guide - Summer 1998</a><br>
          <a href="#"><img src="/gfx/Publications/BG/1998_Summer/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Buyer's Guide - Fall 1998</a><br>
          <a href="#"><img src="/gfx/Publications/BG/1998_Fall/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Buyer's Guide - Holiday 1998</a><br>
          <a href="#"><img src="/gfx/Publications/BG/1998_Holiday/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Buyer's Guide - Spring 1999</a><br>
          <a href="#"><img src="/gfx/Publications/BG/1999_Spring/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Buyer's Guide - Winter 1999</a><br>
          <a href="#"><img src="/gfx/Publications/BG/1999_Winter/01.JPG"></a>
     </div>
</div>
</div>

