<div class="col-4 col-sm-6 col-lg-12">
     <p><center><a class="btn btn-default" href="#" role="button">Upload catalog scans &raquo;</a></center></p>
</div>
<h2>Game catalogs</h2>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Hi-Res Adventures Catalogue 1983</a><br>
          <a href="#"><img src="/gfx/Publications/Catalogues/1983GC/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Catalog 1987</a><br><br>
          <a href="#"><img src="/gfx/Publications/Catalogues/1987_GC/01.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">We're Out to Make Software History</a><br>
          <a href="#"><img src="/gfx/Publications/Catalogues/1987History/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra Fall 1988 Game Catalogue</a><br>
          <a href="#"><img src="/gfx/Publications/Catalogues/1988_GC/01.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra Tenth Anniversary</a><br><br>
          <a href="#"><img src="/gfx/Publications/Catalogues/1990_ANNI/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">The Entire Spectrum of Family Games</a><br>
          <a href="#"><img src="/gfx/Publications/Catalogues/1991_Spectrum/01.JPG"></a>
     </div>
</div>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Discover the Many Worlds of Sierra</a><br>
          <a href="#"><img src="/gfx/Publications/Catalogues/1992_discover/01.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra 15th anniversary catalog, Winter 94-95</a><br>
          <a href="#"><img src="/gfx/Publications/Catalogues/1994_ANNI/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra's Multimedia Lineup, 1992</a><br>
          <a href="#"><img src="/gfx/Publications/Catalogues/1992lineup/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">The CD ROM Catalogue 1994</a><br>
          <a href="#"><img src="/gfx/Publications/Catalogues/1994_CDROM/01.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Multimedia Catalogue 1994-1995</a><br>
          <a href="#"><img src="/gfx/Publications/Catalogues/1994_MM/01.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">The Games Catalogue 1995-1996</a><br>
          <a href="#"><img src="/gfx/Publications/Catalogues/1995_GC/01.jpg"></a>
     </div>
</div>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">The Game Catalogue 1996-1997</a><br>
          <a href="#"><img src="/gfx/Publications/Catalogues/1996_GC/01.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Catalogue 97-98</a><br><br>
          <a href="#"><img src="/gfx/Publications/Catalogues/1997_GC/01.JPG"></a>
          <a href="#">English</a><br>
          <a href="#">Deutsch</a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Catalogue 98 99</a><br><br>
          <a href="#"><img src="/gfx/Publications/Catalogues/1998_GC/01.jpg"></a><br>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Catalogue 1999-2000</a><br><br>
          <a href="#"><img src="/gfx/Publications/Catalogues/1999_GC/01.JPG"></a><br>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Catalogue 2000-2001</a><br><br>
          <a href="#"><img src="/gfx/Publications/Catalogues/2000_GC/01.jpg"></a><br>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">2001 Katalog</a><br><br>
          <a href="#"><img src="/gfx/Publications/Catalogues/2001_Katalog/01.JPG"></a><br>
     </div>
</div>
<h2>Edutainment catalogs</h2>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra Edutainment Catalogue: 1995 1996</a><br>
          <a href="#"><img src="/gfx/Publications/Catalogues/1995_edu/01.JPG"></a>
     </div>
</div>
<h2>Brochures</h2>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">MAC only, 1992</a><br><br>
          <a href="#"><img src="/gfx/Publications/Catalogues/MAC/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra FX 1998</a><br><br>
          <a href="#"><img src="/gfx/Publications/Catalogues/1998FX/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra Studios: Fall 1998/Winter 1999</a><br>
          <a href="#"><img src="/gfx/Publications/Catalogues/1998Studios/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra Originals: Catalogue 1995-1996</a><br>
          <a href="#"><img src="/gfx/Publications/Catalogues/SO1/01cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra Originals: Play the Game (brochure)</a><br>
          <a href="#"><img src="/gfx/Publications/Catalogues/SO2/01cover.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra Originals: Play the Game (booklet)</a><br>
          <a href="#"><img src="/gfx/Publications/Catalogues/SO3/01.JPG"></a>
     </div>
     
</div>

