<h2>Game search</h2>
<div class="well">
<div class="row">
     <div class="col-4 col-sm-6 col-lg-4">
     <div class="well">
          <h2><small>Quick search</small></h2>
          <div class="dropdown">
          <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Select game
          <span class="caret"></span></button>
          <ul class="dropdown-menu">
          <li><a href="#">Game title 1</a></li>
          <li><a href="#">Game title 2</a></li>
          <li><a href="#">Game title 3</a></li>
          <li><a href="#">Game title 4</a></li>
          <li><a href="#">Game title 5</a></li>
          <li><a href="#">Game title 6</a></li>
          <li><a href="#">Game title 7</a></li>
          <li><a href="#">Game title 8</a></li>
          <li><a href="#">Game title 9</a></li>
          <li><a href="#">Game title 10</a></li>
          <li><a href="#">Game title 11</a></li>
          <li><a href="#">Game title 12</a></li>
          <li><a href="#">Game title 13</a></li>
          <li><a href="#">Game title 14</a></li>
          <li><a href="#">Game title 15</a></li>
          <li><a href="#">Game title 16</a></li>
          <li><a href="#">Game title 17</a></li>
          <li><a href="#">Game title 18</a></li>
          <li><a href="#">Game title 19</a></li>
          <li><a href="#">Game title 20</a></li>
          <li><a href="#">Game title 21</a></li>
          </ul>
          </div>
     </div>
     </div>
     <div class="col-4 col-sm-6 col-lg-8">
     <div class="well">
          <h2><small>Custom search</small></h2>
          <div class="row">
          <div class="col-4 col-sm-6 col-lg-4">
               <div class="dropdown">
               <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Select genre
               <span class="caret"></span></button>
               <ul class="dropdown-menu">
               <li><a href="#">Genre 1</a></li>
               <li><a href="#">Genre 2</a></li>
               <li><a href="#">Genre 3</a></li>
               </ul>
               </div>
          </div>
          <div class="col-4 col-sm-6 col-lg-4">
               <div class="dropdown">
               <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Select group
               <span class="caret"></span></button>
               <ul class="dropdown-menu">
               <li><a href="#">Group 1</a></li>
               <li><a href="#">Group 2</a></li>
               <li><a href="#">Group 3</a></li>
               </ul>
               </div>
          </div>
          <div class="col-4 col-sm-6 col-lg-4">
               <div class="dropdown">
               <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Select platform
               <span class="caret"></span></button>
               <ul class="dropdown-menu">
               <li><a href="#">Platform 1</a></li>
               <li><a href="#">Platform 2</a></li>
               <li><a href="#">Platform 3</a></li>
               </ul>
               </div>
          </div>
          </div>
          <p></p>
          <div class="row">
          <div class="col-4 col-sm-6 col-lg-4">
               <div class="dropdown">
               <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Select developer
               <span class="caret"></span></button>
               <ul class="dropdown-menu">
               <li><a href="#">Developer 1</a></li>
               <li><a href="#">Developer 2</a></li>
               <li><a href="#">Developer 3</a></li>
               </ul>
               </div>
          </div>
          <div class="col-4 col-sm-6 col-lg-4">
               <div class="dropdown">
               <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Select publisher
               <span class="caret"></span></button>
               <ul class="dropdown-menu">
               <li><a href="#">Publisher 1</a></li>
               <li><a href="#">Publisher 2</a></li>
               <li><a href="#">Publisher 3</a></li>
               </ul>
               </div>
          </div>
          <div class="col-4 col-sm-6 col-lg-4">
               <div class="dropdown">
               <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Select engine
               <span class="caret"></span></button>
               <ul class="dropdown-menu">
               <li><a href="#">Engine 1</a></li>
               <li><a href="#">Engine 2</a></li>
               <li><a href="#">Engine 3</a></li>
               </ul>
               </div>
          </div>
          </div>
          <div class="row">
          <div class="col-4 col-sm-6 col-lg-12">
               <p><center><a class="btn btn-default" href="#" role="button">Return search results &raquo;</a></center></p>
          </div>
          </div>
     </div>
     </div>
</div>
</div>
<h2>Search results</h2>
<div class="well">
<div class="row">
     <div class="col-4 col-sm-6 col-lg-12">
     <div class="well">
          <h2><small>Here comes a list with search results</small></h2>
     </div>
     </div>
</div>
</div>
