<div id="main" class="container">
    <div class="section row entries bg-primary section-no-margin-bottom">
        <div class="col-lg-6 col-xl-5">
            <div class="row">
                <article class="entry style-grid style-hero hero-md-largest type-post col-md-8 col-lg-12 colheight-sm-1 colheight-md-2 colheight-lg-2 colheight-xl-2">
                    <?= $this->partial('partials/store-display-item.phtml', array('item' => $this->storeItems[0])); ?>
                </article>
                <article class="entry style-grid style-hero type-post col-md-4 col-lg-6 colheight-sm-1">
                    <?= $this->partial('partials/store-display-item.phtml', array('item' => $this->storeItems[1])); ?>
                </article>
                <article class="entry style-grid style-hero type-post col-md-4 col-lg-6 colheight-sm-1">
                    <?= $this->partial('partials/store-display-item.phtml', array('item' => $this->storeItems[2])); ?>
                </article>
            </div>
        </div>
        <div class="col-lg-6 col-xl-7">
            <div class="row">
                <article class="entry style-grid style-hero type-post col-md-4 col-lg-6 colheight-sm-1">
                    <?= $this->partial('partials/store-display-item.phtml', array('item' => $this->storeItems[3])); ?>
                </article>
                <article class="entry style-grid style-hero type-post col-md-4 col-lg-6 colheight-sm-1">
                    <?= $this->partial('partials/store-display-item.phtml', array('item' => $this->storeItems[4])); ?>
                </article>
                <article class="entry style-grid style-hero hero-lg-larger type-post col-md-4 col-lg-6 colheight-sm-1 colheight-lg-2">
                    <?= $this->partial('partials/store-display-item.phtml', array('item' => $this->storeItems[5])); ?>
                </article>
                <article class="entry style-grid style-hero type-post col-md-6 col-lg-6 colheight-sm-1">
                    <?= $this->partial('partials/store-display-item.phtml', array('item' => $this->storeItems[6])); ?>
                </article>
                <article class="entry style-grid style-hero type-post col-md-6 col-lg-6 colheight-sm-1">
                    <?= $this->partial('partials/store-display-item.phtml', array('item' => $this->storeItems[0])); ?>
                </article>
            </div>
        </div>
    </div>
    <div id="content" class="content section row">
        <div class="col-md-9 col-lg-9">
            <div class="row">
                <div class="col-md-4 col-lg-4 md-pull-right">
                    <aside class="widget">
                        <h2 class="widget-title ribbon ribbon-focus"><span>Latest Game Entries</span></h2>
                        <div class="entries row">
                            <?php foreach($this->games as $game) { ?>
                            <article class="type-post style-media-list media col-sm-6 col-md-12">
                                <img src="<?= $game->getCoverArt(); ?>" data-src="<?= $game->getCoverArt(); ?>" data-src-retina="<?= $game->getCoverArt(); ?>" width="80" height="80" class="media-object pull-left" alt="">
                                <noscript>
                                    <img src="<?= $game->getCoverArt(); ?>" alt="">
                                </noscript>
                                <div class="media-body">
                                    <h3  class="entry-title">
                                        <a href="/games/<?= $game->getSlug(); ?>" rel="bookmark"><?= $game->getTitle(); ?></a>
                                    </h3>
                                    <div class="entry-meta">
                                        <span class="entry-date"><a href="/games/<?= $game->getSlug(); ?>"><time datetime="<?= $game->getInsertTs(); ?>"><?= Sierra_Utils_Fuzzy::getFuzzyTime($game->getInsertTs()); ?></time></a></span>
                                    </div>
                                </div>
                            </article>
                            <?php } ?>
                        </div>
                        <div class="more-wrapper">
                            <a href="blog.html" class="btn btn-warning btn-sm">More</a>
                        </div>
                    </aside>
                    <aside class="widget">
                        <h3 class="widget-title ribbon ribbon-focus"><span>Latest Discussion</span></h3>
                        <ul class="entries">
                            <li class="entry style-recent-list type-post">
                                <span class="comments-count-balloon">900</span>
                                <a href="single.html" rel="bookmark" class="entry-title">Ullamco laboris nisi ut aliquip ex ea commodo consequat.</a>
                            </li>
                            <li class="entry style-recent-list type-post">
                                <span class="comments-count-balloon">860</span>
                                <a href="single.html" rel="bookmark" class="entry-title">Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</a>
                            </li>
                            <li class="entry style-recent-list type-post">
                                <span class="comments-count-balloon">1234</span>
                                <a href="single.html" rel="bookmark" class="entry-title">In voluptate velit esse cillum dolore eu fugiat nulla pariatur.</a>
                            </li>
                            <li class="entry style-recent-list type-post">
                                <span class="comments-count-balloon">90</span>
                                <a href="single.html" rel="bookmark" class="entry-title">Duis aute irure dolor in reprehenderit.</a>
                            </li>
                            <li class="entry style-recent-list type-post">
                                <span class="comments-count-balloon">8</span>
                                <a href="single.html" rel="bookmark" class="entry-title">Utempor incididunt ut labore et dolore magna aliqua.</a>
                            </li>
                        </ul>
                    </aside><!--/.widget-->
                    <aside class="widget">
                        <h3 class="widget-title ribbon ribbon-focus"><span>TAGS</span></h3>
                        <div class="tagcloud">
                            <a href="#">Some</a>
                            <a href="#">Tag</a>
                            <a href="#">Goes</a>
                            <a href="#">Here</a>
                            <a href="#">Utempor</a>
                            <a href="#">Incididunt</a>
                            <a href="#">Labore</a>
                            <a href="#">Dolore</a>
                            <a href="#">Magna</a>
                            <a href="#">Aliqua</a>
                            <a href="#">Seddo</a>
                            <a href="#">Siusmod</a>
                            <a href="#">Tempor</a>
                            <a href="#">Incididunt</a>
                            <a href="#">Ut labore</a>
                            <a href="#">Et dolore </a>
                            <a href="#">Magna </a>
                            <a href="#">Aliqua</a>
                            <a href="#">Aliqua</a>
                            <a href="#">Seddo</a>
                            <a href="#">Siusmod</a>
                            <a href="#">Tempor</a>
                            <a href="#">Incididunt</a>
                            <a href="#">Ut labore</a>
                            <a href="#">Et dolore </a>
                            <a href="#">Magna </a>
                            <a href="#">Aliqua</a>
                        </div>
                    </aside><!--/.widget-->
                </div><!--/.col-md-4.col-lg-4.md-pull-right-->
                <div class="bg-base col-md-8 col-lg-8">
                    <h2 class="section-title ribbon ribbon-highlight"><span>What's Hot</span></h2>
                    <div class="entries">
                        <?php foreach($this->newss as $news) { ?>
                        <article class="entry style-large type-post">
                            <figure class="entry-thumbnail hidden-xs">
                                <a href="single.html">
                                    <img src="<?= $news->getImage(); ?>" data-src="<?= $news->getImage(); ?>" data-src-retina="<?= $news->getImage(); ?>" width="680" height="452" alt="">
                                    <noscript>
                                        <img src="<?= $news->getImage(); ?>" alt="">
                                    </noscript>
                                </a>
                            </figure>
                            <header class="entry-header">
                                <h3 class="entry-title">
                                    <a href="single.html" rel="bookmark"><?= $news->getTitle(); ?></a>
                                </h3>
                                <div class="entry-meta">
                                    <span class="author">by <a href="blog.html">John Doe</a></span>
                                    <span class="entry-date"><a href="blog.html">on <time datetime="2013-07-04T23:26:34+00:00">September 20 2013</time></a></span>
                                    <span class="category">In <a href="blog.html">Technology</a></span>
                                </div>
                            </header>
                            <p><?= $news->getBlurb(); ?></p>
                        </article>
                        <?php } ?>
                    </div>
                </div><!--/.bg-base.col-md-8.col-lg-8-->
            </div><!--/.colheight-->
        </div><!--/.col-md-8.col-lg-4-->
        <div class="sidebar col-md-3 col-lg-3">
            <aside class="widget">
                <h2 class="widget-title ribbon"><span>Latest Review</span></h2>
                <div class="entries row">
                    <article class="type-post style-media-list style-review-list media col-sm-6 col-md-12">
                        <div class="style-review-score">
                            80
                        </div>
                        <!-- to disable lazy loading, remove data-src and data-src-retina -->
                        <img src="/img/placeholder.gif" data-src="http://placehold.it/80x80" data-src-retina="http://placehold.it/160x160" width="80" height="80" class="media-object pull-left" alt="">
                        <!--fallback for no javascript browsers-->
                        <noscript>
                            <img src="http://placehold.it/80x80" alt="">
                        </noscript>
                        <div class="media-body">
                            <h3  class="entry-title">
                                <a href="single-full.html" rel="bookmark">xPhone 15s</a>
                            </h3>
                            <p class="small">xPhone Designer: The most secure xPhone Ever?</p>
                        </div>
                    </article>
                    <article class="type-post style-media-list style-review-list media col-sm-6 col-md-12">
                        <div class="style-review-score">
                            79
                        </div>
                        <!-- to disable lazy loading, remove data-src and data-src-retina -->
                        <img src="/img/placeholder.gif" data-src="http://placehold.it/80x80" data-src-retina="http://placehold.it/160x160" width="80" height="80" class="media-object pull-left" alt="">
                        <!--fallback for no javascript browsers-->
                        <noscript>
                            <img src="http://placehold.it/80x80" alt="">
                        </noscript>
                        <div class="media-body">
                            <h3  class="entry-title">
                                <a href="single-full.html" rel="bookmark">xPhone 15c.</a>
                            </h3>
                            <p class="small">Sunt in culpa qui officia deserunt mollit anim id est laborum</p>
                        </div>
                    </article>
                    <article class="type-post style-media-list style-review-list media col-sm-6 col-md-12">
                        <div class="style-review-score">
                            76
                        </div>
                        <!-- to disable lazy loading, remove data-src and data-src-retina -->
                        <img src="/img/placeholder.gif" data-src="http://placehold.it/80x80" data-src-retina="http://placehold.it/160x160" width="80" height="80" class="media-object pull-left" alt="">
                        <!--fallback for no javascript browsers-->
                        <noscript>
                            <img src="http://placehold.it/80x80" alt="">
                        </noscript>
                        <div class="media-body">
                            <h3  class="entry-title">
                                <a href="single-full.html" rel="bookmark">Droid Maxxi.</a>
                            </h3>
                            <p class="small">Laborum sunt in culpa qui officia deserunt mollit anim id est </p>
                        </div>
                    </article>
                    <article class="type-post style-media-list style-review-list media col-sm-6 col-md-12">
                        <div class="style-review-score">
                            79
                        </div>
                        <!-- to disable lazy loading, remove data-src and data-src-retina -->
                        <img src="/img/placeholder.gif" data-src="http://placehold.it/80x80" data-src-retina="http://placehold.it/160x160" width="80" height="80" class="media-object pull-left" alt="">
                        <!--fallback for no javascript browsers-->
                        <noscript>
                            <img src="http://placehold.it/80x80" alt="">
                        </noscript>
                        <div class="media-body">
                            <h3  class="entry-title">
                                <a href="single-full.html" rel="bookmark">NOKIEM Lumpia</a>
                            </h3>
                            <p class="small">Deserunt laborum sunt in culpa qui officia  mollit anim id est </p>
                        </div>
                    </article>
                    <article class="type-post style-media-list style-review-list media col-sm-6 col-md-12">
                        <div class="style-review-score">
                            74
                        </div>
                        <!-- to disable lazy loading, remove data-src and data-src-retina -->
                        <img src="/img/placeholder.gif" data-src="http://placehold.it/80x80" data-src-retina="http://placehold.it/160x160" width="80" height="80" class="media-object pull-left" alt="">
                        <!--fallback for no javascript browsers-->
                        <noscript>
                            <img src="http://placehold.it/80x80" alt="">
                        </noscript>
                        <div class="media-body">
                            <h3  class="entry-title">
                                <a href="single-full.html" rel="bookmark">NFC Dragonfly</a>
                            </h3>
                            <p class="small">Culpa deserunt laborum sunt in qui officia  mollit anim id est </p>
                        </div>
                    </article>
                </div><!--/.entries.colheight-->
                <div class="more-wrapper">
                    <a href="review.html" class="btn btn-warning btn-sm">Review Archive</a>
                </div>
            </aside>
            <div class="collapsible-widgets">
                <aside class="widget">
                    <h2 class="widget-title ribbon"><span>Top Smartphone</span></h2>
                    <ul class="entries">
                        <li class="entry style-score-widget">
                            <div class="score-label entry-title"><a href="single-full.html">xPhone 15s</a></div>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 81%;">
                                    <span>Score:&nbsp;81</span>
                                </div>
                            </div>
                        </li>
                        <li class="entry style-score-widget">
                            <div class="score-label entry-title"><a href="single-full.html">Droid Maxxi</a></div>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 80%;">
                                    <span>Score:&nbsp;80</span>
                                </div>
                            </div>
                        </li>
                        <li class="entry style-score-widget">
                            <div class="score-label entry-title"><a href="single-full.html">Performance</a></div>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 75%;">
                                    <span>Score:&nbsp;76</span>
                                </div>
                            </div>
                        </li>
                        <li class="entry style-score-widget">
                            <div class="score-label entry-title"><a href="single-full.html">NFC Dragonfly</a></div>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 75%;">
                                    <span>Score:&nbsp;75</span>
                                </div>
                            </div>
                        </li>
                        <li class="entry style-score-widget">
                            <div class="score-label entry-title"><a href="single-full.html">Andromeda Titan</a></div>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 70%;">
                                    <span>Score:&nbsp;70</span>
                                </div>
                            </div>
                        </li>
                    </ul>
                </aside>
                <aside class="widget">
                    <h2 class="widget-title ribbon"><span>Top Notebook</span></h2>
                    <ul class="entries">
                        <li class="entry style-score-widget">
                            <div class="score-label entry-title"><a href="single-full.html">xPhone 15s</a></div>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 81%;">
                                    <span>Score:&nbsp;81</span>
                                </div>
                            </div>
                        </li>
                        <li class="entry style-score-widget">
                            <div class="score-label entry-title"><a href="single-full.html">Droid Maxxi</a></div>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 80%;">
                                    <span>Score:&nbsp;80</span>
                                </div>
                            </div>
                        </li>
                        <li class="entry style-score-widget">
                            <div class="score-label entry-title"><a href="single-full.html">Performance</a></div>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 75%;">
                                    <span>Score:&nbsp;76</span>
                                </div>
                            </div>
                        </li>
                        <li class="entry style-score-widget">
                            <div class="score-label entry-title"><a href="single-full.html">NFC Dragonfly</a></div>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 75%;">
                                    <span>Score:&nbsp;75</span>
                                </div>
                            </div>
                        </li>
                        <li class="entry style-score-widget">
                            <div class="score-label entry-title"><a href="single-full.html">Andromeda Titan</a></div>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 70%;">
                                    <span>Score:&nbsp;70</span>
                                </div>
                            </div>
                        </li>
                    </ul>
                </aside>
            </div>
            <aside class="widget widget_calendar">
                <h3 class="widget-title ribbon"><span>Calendar</span></h3>
                <div id="calendar_wrap">
                    <table id="wp-calendar">
                        <caption>July 2013</caption>
                        <thead>
                            <tr>
                                <th scope="col" title="Monday">M</th>
                                <th scope="col" title="Tuesday">T</th>
                                <th scope="col" title="Wednesday">W</th>
                                <th scope="col" title="Thursday">T</th>
                                <th scope="col" title="Friday">F</th>
                                <th scope="col" title="Saturday">S</th>
                                <th scope="col" title="Sunday">S</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <td colspan="3" id="prev"><a href="#" title="View posts for March 2013">&laquo; Mar</a></td>
                                <td class="pad">&nbsp;</td>
                                <td colspan="3" id="next"><a href="#" title="View posts for March 2013">Aug &raquo;</a></td>
                            </tr>
                        </tfoot>
                        <tbody>
                            <tr><td>1</td><td>2</td><td>3</td><td>4</td><td>5</td><td>6</td><td>7</td>
                            </tr>
                            <tr>
                                <td>8</td><td>9</td><td>10</td><td>11</td><td>12</td><td>13</td><td>14</td>
                            </tr>
                            <tr>
                                <td>15</td><td>16</td><td>17</td><td>18</td><td>19</td><td>20</td><td>21</td>
                            </tr>
                            <tr>
                                <td>22</td><td>23</td><td>24</td><td>25</td><td>26</td><td>27</td><td>28</td>
                            </tr>
                            <tr>
                                <td>29</td><td id="today">30</td><td>31</td>
                                <td class="pad" colspan="4">&nbsp;</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </aside>
            <aside class="widget">
                <h3 class="widget-title ribbon"><span>Special Coverage</span></h3>
                <ul class="entries coverageList aligncenter">
                    <li><a href="blog.html">#xPhone launch event</a></li>
                    <li><a href="blog.html">#WCDC 2013</a></li>
                    <li><a href="blog.html">#Nokiem bought by Macrosoft</a></li>
                    <li><a href="blog.html">#Blueberry JUMP 2013</a></li>
                    <li><a href="blog.html">#CONFEST 2013</a></li>
                    <li><a href="blog.html">#Ullamco laboris nisi ut. </a></li>
                    <li><a href="blog.html">#Eliquip ex ea commodo consequat.</a></li>
                    <li><a href="blog.html">#Duis aute irure dolor in.</a></li>
                    <li><a href="blog.html">#Reprehenderit in voluptate</a></li>
                    <li><a href="blog.html">#Velit esse Ullamco laboris.</a></li>
                </ul>
            </aside><!--/.widget-->
        </div><!--/.sidebar.col-md-3.col-lg-3-->
    </div><!--/.row.content-->
    <div id="coverageCarousel" class="section bg-primary carousel carousel slide">
        <h2 class="section-title ribbon ribbon-highlight"><span>&nbsp;</span></h2>
        <div class="carousel-inner">
            <div class="item active">
                <h2 class="section-title ribbon ribbon-highlight"><a href="blog.html"> xPhone launch event</a></h2>
                <div class="row entries">
                    <article class="entry style-grid type-post col-md-6 col-lg-3 colheight-sm-1">
                        <header class="entry-header">
                            <p class="small"><a href="blog.html">Review</a></p>
                            <h3 class="entry-title"><a href="single.html">xPhone first hand: Check out, this might be the right phone for you</a> </h3>
                            <div class="entry-meta">
                                <span class="entry-date"><a href="blog.html"><time datetime="2013-07-04T23:26:34+00:00">20 hours ago</time></a></span>
                                <span class="entry-author"> by <a href="blog.html">John Doe</a></span>
                            </div>
                        </header>
                        <figure class="entry-thumbnail">
                            <a href="single.html" class="overlay overlay-primary"></a>
                            <!-- to disable lazy loading, remove data-src and data-src-retina -->
                            <img src="/img/placeholder.gif" data-src="http://placehold.it/480x280" data-src-retina="http://placehold.it/720x420" width="480" height="280" alt="">
                            <!--fallback for no javascript browsers-->
                            <noscript>
                                <img src="http://placehold.it/480x280" alt="">
                            </noscript>
                        </figure>
                    </article>
                    <article class="entry style-grid type-post col-md-6 col-lg-3 colheight-sm-1">
                        <header class="entry-header">
                            <p class="small"><a href="blog.html">Event Report</a></p>
                            <h3 class="entry-title"><a href="single.html">The rumor was not a joke, lorem ispsum dolor sit amet constactetiour.</a> </h3>
                            <div class="entry-meta">
                                <span class="entry-date"><a href="blog.html"><time datetime="2013-07-04T23:26:34+00:00">20 hours ago</time></a></span>
                                <span class="entry-author"> by <a href="blog.html">John Doe</a></span>
                            </div>
                        </header>
                        <figure class="entry-thumbnail">
                            <a href="single.html" class="overlay overlay-primary"></a>
                            <!-- to disable lazy loading, remove data-src and data-src-retina -->
                            <img src="/img/placeholder.gif" data-src="http://placehold.it/680x452" data-src-retina="http://placehold.it/1024x680" width="680" height="452" alt="">
                            <!--fallback for no javascript browsers-->
                            <noscript>
                                <img src="http://placehold.it/680x452" alt="">
                            </noscript>
                        </figure>
                    </article>
                    <article class="entry style-grid type-post col-md-6 col-lg-3 colheight-sm-1">
                        <header class="entry-header">
                            <p class="small"><a href="blog.html">Event Report</a></p>
                            <h3 class="entry-title"><a href="single.html">The Event is starting Now. Grab your popcorn, beer and notes.</a> </h3>
                            <div class="entry-meta">
                                <span class="entry-date"><a href="blog.html"><time datetime="2013-07-04T23:26:34+00:00">20 hours ago</time></a></span>
                                <span class="entry-author"> by <a href="blog.html">John Doe</a></span>
                            </div>
                        </header>
                        <figure class="entry-thumbnail">
                            <a href="single.html" class="overlay overlay-primary"></a>
                            <!-- to disable lazy loading, remove data-src and data-src-retina -->
                            <img src="/img/placeholder.gif" data-src="http://placehold.it/480x280" data-src-retina="http://placehold.it/720x420" width="480" height="280" alt="">
                            <!--fallback for no javascript browsers-->
                            <noscript>
                                <img src="http://placehold.it/480x280" alt="">
                            </noscript>
                        </figure>
                    </article>
                    <article class="entry style-grid type-post col-md-6 col-lg-3 colheight-sm-1">
                        <header class="entry-header">
                            <p class="small"><a href="blog.html">Speculation</a></p>
                            <h3 class="entry-title"><a href="single.html">Rumor: The long awaited update for Retina Display is ready to be annaunced on the next event held by them</a> </h3>
                            <div class="entry-meta">
                                <span class="entry-date"><a href="blog.html"><time datetime="2013-07-04T23:26:34+00:00">20 hours ago</time></a></span>
                                <span class="entry-author"> by <a href="blog.html">John Doe</a></span>
                            </div>
                        </header>
                        <figure class="entry-thumbnail">
                            <a href="single.html" class="overlay overlay-primary"></a>
                            <!-- to disable lazy loading, remove data-src and data-src-retina -->
                            <img src="/img/placeholder.gif" data-src="http://placehold.it/480x280" data-src-retina="http://placehold.it/720x420" width="480" height="280" alt="">
                            <!--fallback for no javascript browsers-->
                            <noscript>
                                <img src="http://placehold.it/480x280" alt="">
                            </noscript>
                        </figure>
                    </article>
                </div><!--/.row.entries-->
            </div><!--/.item-->
            <div class="item">
                <h2 class="section-title ribbon ribbon-highlight"><a href="blog.html"> #WCDC 2013</a></h2>
                <div class="row entries">
                    <article class="entry style-grid type-post col-md-6 col-lg-3 colheight-sm-1">
                        <header class="entry-header">
                            <p class="small"><a href="blog.html">Event Report</a></p>
                            <h3 class="entry-title"><a href="single.html">The Event is starting Now. Grab your popcorn, beer and notes.</a> </h3>
                            <div class="entry-meta">
                                <span class="entry-date"><a href="blog.html"><time datetime="2013-07-04T23:26:34+00:00">20 hours ago</time></a></span>
                                <span class="entry-author"> by <a href="blog.html">John Doe</a></span>
                            </div>
                        </header>
                        <figure class="entry-thumbnail">
                            <a href="single.html" class="overlay overlay-primary"></a>
                            <!-- to disable lazy loading, remove data-src and data-src-retina -->
                            <img src="/img/placeholder.gif" data-src="http://placehold.it/480x280" data-src-retina="http://placehold.it/720x420" width="480" height="280" alt="">
                            <!--fallback for no javascript browsers-->
                            <noscript>
                                <img src="http://placehold.it/480x280" alt="">
                            </noscript>
                        </figure>
                    </article>
                    <article class="entry style-grid type-post col-md-6 col-lg-3 colheight-sm-1">
                        <header class="entry-header">
                            <p class="small"><a href="blog.html">Speculation</a></p>
                            <h3 class="entry-title"><a href="single.html">Rumor: The long awaited update for Retina Display is ready to be annaunced on the next event held by them</a> </h3>
                            <div class="entry-meta">
                                <span class="entry-date"><a href="blog.html"><time datetime="2013-07-04T23:26:34+00:00">20 hours ago</time></a></span>
                                <span class="entry-author"> by <a href="blog.html">John Doe</a></span>
                            </div>
                        </header>
                        <figure class="entry-thumbnail">
                            <a href="single.html" class="overlay overlay-primary"></a>
                            <!-- to disable lazy loading, remove data-src and data-src-retina -->
                            <img src="/img/placeholder.gif" data-src="http://placehold.it/480x280" data-src-retina="http://placehold.it/720x420" width="480" height="280" alt="">
                            <!--fallback for no javascript browsers-->
                            <noscript>
                                <img src="http://placehold.it/480x280" alt="">
                            </noscript>
                        </figure>
                    </article>
                    <article class="entry style-grid type-post col-md-6 col-lg-3 colheight-sm-1">
                        <header class="entry-header">
                            <p class="small"><a href="blog.html">Review</a></p>
                            <h3 class="entry-title"><a href="single.html">xPhone first hand: Check out, this might be the right phone for you</a> </h3>
                            <div class="entry-meta">
                                <span class="entry-date"><a href="blog.html"><time datetime="2013-07-04T23:26:34+00:00">20 hours ago</time></a></span>
                                <span class="entry-author"> by <a href="blog.html">John Doe</a></span>
                            </div>
                        </header>
                        <figure class="entry-thumbnail">
                            <a href="single.html" class="overlay overlay-primary"></a>
                            <!-- to disable lazy loading, remove data-src and data-src-retina -->
                            <img src="/img/placeholder.gif" data-src="http://placehold.it/480x280" data-src-retina="http://placehold.it/720x420" width="480" height="280" alt="">
                            <!--fallback for no javascript browsers-->
                            <noscript>
                                <img src="http://placehold.it/480x280" alt="">
                            </noscript>
                        </figure>
                    </article>
                    <article class="entry style-grid type-post col-md-6 col-lg-3 colheight-sm-1">
                        <header class="entry-header">
                            <p class="small"><a href="blog.html">Event Report</a></p>
                            <h3 class="entry-title"><a href="single.html">The rumor was not a joke, lorem ispsum dolor sit amet constactetiour.</a> </h3>
                            <div class="entry-meta">
                                <span class="entry-date"><a href="blog.html"><time datetime="2013-07-04T23:26:34+00:00">20 hours ago</time></a></span>
                                <span class="entry-author"> by <a href="blog.html">John Doe</a></span>
                            </div>
                        </header>
                        <figure class="entry-thumbnail">
                            <a href="single.html" class="overlay overlay-primary"></a>
                            <!-- to disable lazy loading, remove data-src and data-src-retina -->
                            <img src="/img/placeholder.gif" data-src="http://placehold.it/680x452" data-src-retina="http://placehold.it/1024x680" width="680" height="452" alt="">
                            <!--fallback for no javascript browsers-->
                            <noscript>
                                <img src="http://placehold.it/680x452" alt="">
                            </noscript>
                        </figure>
                    </article>
                </div><!--/.row.entries-->
            </div><!--/.item-->
        </div><!--/.carousel-inner-->
        <a class="left carousel-control" href="#coverageCarousel" data-slide="prev">
            <span class="icon icon-angle-left"></span>
        </a>
        <a class="right carousel-control" href="#coverageCarousel" data-slide="next">
            <span class="icon icon-angle-right"></span>
        </a>
    </div>
    <div class="section content bg-base">
        <h2 class="section-title ribbon"><span>What's you should know</span></h2>
        <div class="entries">
            <div class="row">
                <article class="entry type-post style-thumbnail-text col-sm-6 col-md-2 colheight-sm-1">
                    <div class="entry-meta">
                        <span class="category"><a href="blog.html">Social Media</a></span>
                    </div>
                    <h3 class="entry-title">
                        <a href="single.html" rel="bookmark">Postman will send alerts to your phone about popular people and their shouts.</a>
                    </h3>
                </article>
                <article class="entry type-post style-thumbnail-text col-sm-6 col-md-2 colheight-sm-1">
                    <div class="entry-meta">
                        <span class="category"><a href="blog.html">Politic</a></span>
                    </div>
                    <h3 class="entry-title">
                        <a href="single.html" rel="bookmark">Better to remain silent and be thought a fool than to speak out and remove all doubt, says Abraham L</a>
                    </h3>
                </article>
                <article class="entry type-post style-thumbnail-text col-sm-6 col-md-2 colheight-sm-1">
                    <div class="entry-meta">
                        <span class="category"><a href="blog.html">Sports</a></span>
                    </div>
                    <h3 class="entry-title">
                        <a href="single.html" rel="bookmark">I always work with a goal - and the goal is to improve as a player and a person, says Rafael Nadal</a>
                    </h3>
                </article>
                <article class="entry type-post style-thumbnail-text col-sm-6 col-md-2 colheight-sm-1">
                    <div class="entry-meta">
                        <span class="category"><a href="blog.html">Entertainment</a></span>
                    </div>
                    <h3 class="entry-title">
                        <a href="single.html" rel="bookmark">Curt Cobain: Wanting to be someone else is a waste of the person you are.</a>
                    </h3>
                </article>
                <article class="entry type-post style-thumbnail-text col-sm-6 col-md-2 colheight-sm-1">
                    <div class="entry-meta">
                        <span class="category"><a href="blog.html">Technology</a></span>
                    </div>
                    <h3 class="entry-title">
                        <a href="single.html" rel="bookmark">Innovation distinguishes between a leader and a follower - Steve Jobs</a>
                    </h3>
                </article>
                <article class="entry type-post style-thumbnail-text col-sm-6 col-md-2 colheight-sm-1">
                    <div class="entry-meta">
                        <span class="category"><a href="blog.html">Tactical</a></span>
                    </div>
                    <h3 class="entry-title">
                        <a href="single.html" rel="bookmark">Know your enemy and know yourself and you can fight a hundred battles without disaster - Tzun Zu.</a>
                    </h3>
                </article>
                <article class="entry type-post style-thumbnail-text col-sm-6 col-md-2 colheight-sm-1">
                    <div class="entry-meta">
                        <span class="category"><a href="blog.html">Entertainment</a></span>
                    </div>
                    <h3 class="entry-title">
                        <a href="single.html" rel="bookmark">Curt Cobain: Wanting to be someone else is a waste of the person you are.</a>
                    </h3>
                </article>
                <article class="entry type-post style-thumbnail-text col-sm-6 col-md-2 colheight-sm-1">
                    <div class="entry-meta">
                        <span class="category"><a href="blog.html">Technology</a></span>
                    </div>
                    <h3 class="entry-title">
                        <a href="single.html" rel="bookmark">Innovation distinguishes between a leader and a follower - Steve Jobs</a>
                    </h3>
                </article>
                <article class="entry type-post style-thumbnail-text col-sm-6 col-md-2 colheight-sm-1">
                    <div class="entry-meta">
                        <span class="category"><a href="blog.html">Tactical</a></span>
                    </div>
                    <h3 class="entry-title">
                        <a href="single.html" rel="bookmark">Know your enemy and know yourself and you can fight a hundred battles without disaster - Tzun Zu.</a>
                    </h3>
                </article>
                <article class="entry type-post style-thumbnail-text col-sm-6 col-md-2 colheight-sm-1">
                    <div class="entry-meta">
                        <span class="category"><a href="blog.html">Social Media</a></span>
                    </div>
                    <h3 class="entry-title">
                        <a href="single.html" rel="bookmark">Postman will send alerts to your phone about popular people and their shouts.</a>
                    </h3>
                </article>
                <article class="entry type-post style-thumbnail-text col-sm-6 col-md-2 colheight-sm-1">
                    <div class="entry-meta">
                        <span class="category"><a href="blog.html">Politic</a></span>
                    </div>
                    <h3 class="entry-title">
                        <a href="single.html" rel="bookmark">Better to remain silent and be thought a fool than to speak out and remove all doubt, says Abraham L</a>
                    </h3>
                </article>
                <article class="entry type-post style-thumbnail-text col-sm-6 col-md-2 colheight-sm-1">
                    <div class="entry-meta">
                        <span class="category"><a href="blog.html">Sports</a></span>
                    </div>
                    <h3 class="entry-title">
                        <a href="single.html" rel="bookmark">I always work with a goal - and the goal is to improve as a player and a person, says Rafael Nadal</a>
                    </h3>
                </article>
                <article class="entry type-post style-thumbnail-text col-sm-6 col-md-2 colheight-sm-1">
                    <div class="entry-meta">
                        <span class="category"><a href="blog.html">Politic</a></span>
                    </div>
                    <h3 class="entry-title">
                        <a href="single.html" rel="bookmark">Better to remain silent and be thought a fool than to speak out and remove all doubt, says Abraham L</a>
                    </h3>
                </article>
                <article class="entry type-post style-thumbnail-text col-sm-6 col-md-2 colheight-sm-1">
                    <div class="entry-meta">
                        <span class="category"><a href="blog.html">Sports</a></span>
                    </div>
                    <h3 class="entry-title">
                        <a href="single.html" rel="bookmark">I always work with a goal - and the goal is to improve as a player and a person, says Rafael Nadal</a>
                    </h3>
                </article>
                <article class="entry type-post style-thumbnail-text col-sm-6 col-md-2 colheight-sm-1">
                    <div class="entry-meta">
                        <span class="category"><a href="blog.html">Entertainment</a></span>
                    </div>
                    <h3 class="entry-title">
                        <a href="single.html" rel="bookmark">Curt Cobain: Wanting to be someone else is a waste of the person you are.</a>
                    </h3>
                </article>
                <article class="entry type-post style-thumbnail-text col-sm-6 col-md-2 colheight-sm-1">
                    <div class="entry-meta">
                        <span class="category"><a href="blog.html">Technology</a></span>
                    </div>
                    <h3 class="entry-title">
                        <a href="single.html" rel="bookmark">Innovation distinguishes between a leader and a follower - Steve Jobs</a>
                    </h3>
                </article>
                <article class="entry type-post style-thumbnail-text col-sm-6 col-md-2 colheight-sm-1">
                    <div class="entry-meta">
                        <span class="category"><a href="blog.html">Tactical</a></span>
                    </div>
                    <h3 class="entry-title">
                        <a href="single.html" rel="bookmark">Know your enemy and know yourself and you can fight a hundred battles without disaster - Tzun Zu.</a>
                    </h3>
                </article>
                <article class="entry type-post style-thumbnail-text col-sm-6 col-md-2 colheight-sm-1">
                    <div class="entry-meta">
                        <span class="category"><a href="blog.html">Social Media</a></span>
                    </div>
                    <h3 class="entry-title">
                        <a href="single.html" rel="bookmark">Postman will send alerts to your phone about popular people and their shouts.</a>
                    </h3>
                </article>
            </div><!--row.-->
        </div><!--entries.-->
    </div><!--.section.content.content-secondary-->
</div><!--#main.container-->


<!--
<div class="row">

<div class="col-6 col-sm-6 col-lg-9">
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
<ol class="carousel-indicators">
<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
<li data-target="#carousel-example-generic" data-slide-to="1"></li>
<li data-target="#carousel-example-generic" data-slide-to="2"></li>
<li data-target="#carousel-example-generic" data-slide-to="3"></li>
<li data-target="#carousel-example-generic" data-slide-to="4"></li>
</ol>

<div class="carousel-inner">
<div class="item active">
<img src="gfx/home/carousel/sierrachest.jpg" alt="First slide">
</div>
<div class="item">
<a href="http://www.sierra.com" target="_blank"><img src="gfx/home/carousel/sierra.jpg" alt="Second slide"></a>
</div>
<div class="item">
<a href="http://www.artofsierra.com" target="_blank"><img src="gfx/home/carousel/artofsierra.jpg" alt="Third slide"></a>
</div>
<div class="item">
<a href="http://www.sierrahelp.com" target="_blank"><img src="gfx/home/carousel/sierrahelp.jpg" alt="Fourth slide"></a>
</div>
<div class="item">
<a href="http://hero-u.com/" target="_blank"><img src="gfx/home/carousel/hero-u.jpg" alt="Fifth slide"></a>
</div>
</div>

<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
<span class="glyphicon glyphicon-chevron-left"></span>
</a>
<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
<span class="glyphicon glyphicon-chevron-right"></span>
</a>
</div>
</div>

<div class="col-2 col-sm-2 col-lg-3">
<p><a href="http://www.gog.com/?pp=fae120307794af3766ea7c64b70700f66e540456" target="_blank"><img src="gfx/home/promo/GOG-300x600.PNG"></a></p>
</div>

</div>
<div class="row">
<div class="col-4 col-sm-6 col-lg-6">
  <h2>News</h2>
  <div class="well">
      <p>
      <div class="row">
        <div class="col-4 col-sm-4 col-lg-4"><img src="gfx/blog/icons/sierrachest.JPG"></div>
        <div class="col-4 col-sm-4 col-lg-8">Here comes the title, short description and link to the news</div>
      </div>
      </p>
      <p>
      <div class="row">
        <div class="col-4 col-sm-4 col-lg-4"><img src="gfx/blog/icons/sierrachest.JPG"></div>
        <div class="col-4 col-sm-4 col-lg-8">Here comes the title, short description and link to the news</div>
      </div>
      </p>
      <p>
      <div class="row">
        <div class="col-4 col-sm-4 col-lg-4"><img src="gfx/blog/icons/sierrachest.JPG"></div>
        <div class="col-4 col-sm-4 col-lg-8">Here comes the title, short description and link to the news</div>
      </div>
      </p>
      <p>
      <div class="row">
        <div class="col-4 col-sm-4 col-lg-4"><img src="gfx/blog/icons/sierrachest.JPG"></div>
        <div class="col-4 col-sm-4 col-lg-8">Here comes the title, short description and link to the news</div>
      </div>
      </p>
      <p>
      <div class="row">
        <div class="col-4 col-sm-4 col-lg-4"><img src="gfx/blog/icons/sierrachest.JPG"></div>
        <div class="col-4 col-sm-4 col-lg-8">Here comes the title, short description and link to the news</div>
      </div>
      </p>
      <p>
      <div class="row">
        <div class="col-4 col-sm-4 col-lg-4"><img src="gfx/blog/icons/sierrachest.JPG"></div>
        <div class="col-4 col-sm-4 col-lg-8">Here comes the title, short description and link to the news</div>
      </div>
      </p>
      <p>
      <div class="row">
        <div class="col-4 col-sm-4 col-lg-4"><img src="gfx/blog/icons/sierrachest.JPG"></div>
        <div class="col-4 col-sm-4 col-lg-8">Here comes the title, short description and link to the news</div>
      </div>
      </p>
      <p>
      <div class="row">
        <div class="col-4 col-sm-4 col-lg-4"><img src="gfx/blog/icons/sierrachest.JPG"></div>
        <div class="col-4 col-sm-4 col-lg-8">Here comes the title, short description and link to the news</div>
      </div>
      </p>
      <p>
      <div class="row">
        <div class="col-4 col-sm-4 col-lg-4"><img src="gfx/blog/icons/sierrachest.JPG"></div>
        <div class="col-4 col-sm-4 col-lg-8">Here comes the title, short description and link to the news</div>
      </div>
      </p>
      <p>
      <div class="row">
        <div class="col-4 col-sm-4 col-lg-4"><img src="gfx/blog/icons/sierrachest.JPG"></div>
        <div class="col-4 col-sm-4 col-lg-8">Here comes the title, short description and link to the news</div>
      </div>
      </p>
      <p>
      <a class="btn btn-default" href="#" role="button">More news &raquo;</a>
      </p>
    </div>
    </div>
    <div class="col-6 col-sm-6 col-lg-3">
      <h2>Latest games</h2>
      <div class="well">
      - Game 1<br>
      - Game 2<br>
      - Game 3<br>
      - Game 4<br>
      - Game 5<br>
      <p><a class="btn btn-default" href="#" role="button">Search games &raquo;</a></p>
      </div>
    </div>
    <div class="col-6 col-sm-6 col-lg-3">
      <h2>Most wanted</h2>
      <div class="well">
      - Game 1<br>
      - Game 2<br>
      - Game 3<br>
      - Game 4<br>
      - Game 5<br>
      <p><a class="btn btn-default" href="#" role="button">Vote &raquo;</a></p>
      </div>
    </div>
    <div class="col-6 col-sm-6 col-lg-3">
      <h2>Latest box art</h2>
      <div class="well">
      <p>- Game 1</p>
      <p>- Game 2</p>
      <p>- Game 3</p>
      <p>- Game 4</p>
      <p>- Game 5</p>
      </div>
    </div>
    <div class="col-6 col-sm-6 col-lg-3">
      <h2>Latest screen shots</h2>
      <div class="well">
      <p>- Game 1</p>
      <p>- Game 2</p>
      <p>- Game 3</p>
      <p>- Game 4</p>
      <p>- Game 5</p>
      </div>
    </div>
    <div class="col-6 col-sm-6 col-lg-3">
      <h2>Latest reviews</h2>
      <div class="well">
      <p>- Game 1</p>
      <p>- Game 2</p>
      <p>- Game 3</p>
      <p>- Game 4</p>
      <p>- Game 5</p>
      <p><a class="btn btn-default" href="#" role="button">More reviews &raquo;</a></p>
      </div>
    </div>
    <div class="col-6 col-sm-6 col-lg-3">
      <h2>Latest music</h2>
      <div class="well">
      <p>- Game 1</p>
      <p>- Game 2</p>
      <p>- Game 3</p>
      <p>- Game 4</p>
      <p>- Game 5</p>
    <p><a class="btn btn-default" href="#" role="button">Music player &raquo;</a></p>
    </div>
    </div>
    <div class="col-6 col-sm-6 col-lg-6">
      <h2>Top members (quarter)</h2>
      <div class="well">
      <div row>
      <div class="col-6 col-sm-6 col-lg-6">
        <p>- Member 1 + score</p>
        <p>- Member 2 + score</p>
        <p>- Member 3 + score</p>
        <p>- Member 4 + score</p>
        <p>- Member 5 + score</p>
      </div>
      <div class="col-6 col-sm-6 col-lg-6">
        <p>- Member 6 + score</p>
        <p>- Member 7 + score</p>
        <p>- Member 8 + score</p>
        <p>- Member 9 + score</p>
        <p>- Member 10 + score</p>
      </div>
      </div>
      <p><a class="btn btn-default" href="#" role="button">Member stats &raquo;</a></p>
      </div>
    </div>
</div>
    <div class="col-6 col-sm-6 col-lg-12">
      <h2>Latest store items</h2>
      <div class="well">
      <div row>
        <div class="col-6 col-sm-6 col-lg-2"><img src="/gfx/store/98_01.jpg"></div>
        <div class="col-6 col-sm-6 col-lg-2"><img src="/gfx/store/99_01.jpg"></div>
        <div class="col-6 col-sm-6 col-lg-2"><img src="/gfx/store/100_01.jpg"></div>
        <div class="col-6 col-sm-6 col-lg-2"><img src="/gfx/store/101_01.jpg"></div>
        <div class="col-6 col-sm-6 col-lg-2"><img src="/gfx/store/102_01.jpg"></div>
        <div class="col-6 col-sm-6 col-lg-2"><img src="/gfx/store/103_01.jpg"></div>
      <p><a class="btn btn-default" href="#" role="button">Search store &raquo;</a></p>
      </div>
      </div>
    </div>
-->

