<div class="row">

<!--Carousel -->

<div class="col-6 col-sm-6 col-lg-9">
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
    <li data-target="#carousel-example-generic" data-slide-to="4"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img src="gfx/home/carousel/sierrachest.jpg" alt="First slide">
      <!--<div class="carousel-caption">
          <h3>Caption Text</h3>
      </div> -->
    </div>
    <div class="item">
      <a href="http://www.sierra.com" target="_blank"><img src="gfx/home/carousel/sierra.jpg" alt="Second slide"></a>
    </div>
    <div class="item">
      <a href="http://www.artofsierra.com" target="_blank"><img src="gfx/home/carousel/artofsierra.jpg" alt="Third slide"></a>
    </div>
    <div class="item">
      <a href="http://www.sierrahelp.com" target="_blank"><img src="gfx/home/carousel/sierrahelp.jpg" alt="Fourth slide"></a>
    </div>
    <div class="item">
      <a href="http://hero-u.com/" target="_blank"><img src="gfx/home/carousel/hero-u.jpg" alt="Fifth slide"></a>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

</div> <!-- /Carousel -->

<!--Promos -->

<div class="col-2 col-sm-2 col-lg-3">
     <!--<h2>Heading</h2> -->
     <p><a href="http://www.gog.com/?pp=fae120307794af3766ea7c64b70700f66e540456" target="_blank"><img src="gfx/home/promo/GOG-300x600.PNG"></a></p>
     </div><!--/span-->
     
<!-- /Promos -->

</div>     <!-- row-->

<div class="row">
     <div class="col-4 col-sm-6 col-lg-6">
          <h2>News</h2>
          <div class="well">
              <p>
              <div class="row">
                <div class="col-4 col-sm-4 col-lg-4"><img src="gfx/blog/icons/sierrachest.JPG"></div>
                <div class="col-4 col-sm-4 col-lg-8">Here comes the title, short description and link to the news</div>
              </div>
              </p>
              <p>
              <div class="row">
                <div class="col-4 col-sm-4 col-lg-4"><img src="gfx/blog/icons/sierrachest.JPG"></div>
                <div class="col-4 col-sm-4 col-lg-8">Here comes the title, short description and link to the news</div>
              </div>
              </p>
              <p>
              <div class="row">
                <div class="col-4 col-sm-4 col-lg-4"><img src="gfx/blog/icons/sierrachest.JPG"></div>
                <div class="col-4 col-sm-4 col-lg-8">Here comes the title, short description and link to the news</div>
              </div>
              </p>
              <p>
              <div class="row">
                <div class="col-4 col-sm-4 col-lg-4"><img src="gfx/blog/icons/sierrachest.JPG"></div>
                <div class="col-4 col-sm-4 col-lg-8">Here comes the title, short description and link to the news</div>
              </div>
              </p>
              <p>
              <div class="row">
                <div class="col-4 col-sm-4 col-lg-4"><img src="gfx/blog/icons/sierrachest.JPG"></div>
                <div class="col-4 col-sm-4 col-lg-8">Here comes the title, short description and link to the news</div>
              </div>
              </p>
              <p>
              <div class="row">
                <div class="col-4 col-sm-4 col-lg-4"><img src="gfx/blog/icons/sierrachest.JPG"></div>
                <div class="col-4 col-sm-4 col-lg-8">Here comes the title, short description and link to the news</div>
              </div>
              </p>
              <p>
              <div class="row">
                <div class="col-4 col-sm-4 col-lg-4"><img src="gfx/blog/icons/sierrachest.JPG"></div>
                <div class="col-4 col-sm-4 col-lg-8">Here comes the title, short description and link to the news</div>
              </div>
              </p>
              <p>
              <div class="row">
                <div class="col-4 col-sm-4 col-lg-4"><img src="gfx/blog/icons/sierrachest.JPG"></div>
                <div class="col-4 col-sm-4 col-lg-8">Here comes the title, short description and link to the news</div>
              </div>
              </p>
              <p>
              <div class="row">
                <div class="col-4 col-sm-4 col-lg-4"><img src="gfx/blog/icons/sierrachest.JPG"></div>
                <div class="col-4 col-sm-4 col-lg-8">Here comes the title, short description and link to the news</div>
              </div>
              </p>
              <p>
              <div class="row">
                <div class="col-4 col-sm-4 col-lg-4"><img src="gfx/blog/icons/sierrachest.JPG"></div>
                <div class="col-4 col-sm-4 col-lg-8">Here comes the title, short description and link to the news</div>
              </div>
              </p>
              <p>
              <a class="btn btn-default" href="#" role="button">More news &raquo;</a>
              </p>
            </div>
            </div>
            <div class="col-6 col-sm-6 col-lg-3">
              <h2>Latest games</h2>
              <div class="well">
              - Game 1<br>
              - Game 2<br>
              - Game 3<br>
              - Game 4<br>
              - Game 5<br>
              <p><a class="btn btn-default" href="#" role="button">Search games &raquo;</a></p>
              </div>
            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-3">
              <h2>Most wanted</h2>
              <div class="well">
              - Game 1<br>
              - Game 2<br>
              - Game 3<br>
              - Game 4<br>
              - Game 5<br>
              <p><a class="btn btn-default" href="#" role="button">Vote &raquo;</a></p>
              </div>
            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-3">
              <h2>Latest box art</h2>
              <div class="well">
              <p>- Game 1</p>
              <p>- Game 2</p>
              <p>- Game 3</p>
              <p>- Game 4</p>
              <p>- Game 5</p>
              </div>
            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-3">
              <h2>Latest screen shots</h2>
              <div class="well">
              <p>- Game 1</p>
              <p>- Game 2</p>
              <p>- Game 3</p>
              <p>- Game 4</p>
              <p>- Game 5</p>
              </div>
            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-3">
              <h2>Latest reviews</h2>
              <div class="well">
              <p>- Game 1</p>
              <p>- Game 2</p>
              <p>- Game 3</p>
              <p>- Game 4</p>
              <p>- Game 5</p>
              <p><a class="btn btn-default" href="#" role="button">More reviews &raquo;</a></p>
              </div>
            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-3">
              <h2>Latest music</h2>
              <div class="well">
              <p>- Game 1</p>
              <p>- Game 2</p>
              <p>- Game 3</p>
              <p>- Game 4</p>
              <p>- Game 5</p>
            <p><a class="btn btn-default" href="#" role="button">Music player &raquo;</a></p>
            </div>
            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-6">
              <h2>Top members (quarter)</h2>
              <div class="well">
              <div row>
              <div class="col-6 col-sm-6 col-lg-6">
                <p>- Member 1 + score</p>
                <p>- Member 2 + score</p>
                <p>- Member 3 + score</p>
                <p>- Member 4 + score</p>
                <p>- Member 5 + score</p>
              </div>
              <div class="col-6 col-sm-6 col-lg-6">
                <p>- Member 6 + score</p>
                <p>- Member 7 + score</p>
                <p>- Member 8 + score</p>
                <p>- Member 9 + score</p>
                <p>- Member 10 + score</p>
              </div>
              </div>    <!--/row-->
              <p><a class="btn btn-default" href="#" role="button">Member stats &raquo;</a></p>
              </div>
            </div><!--/span-->
</div>
            <div class="col-6 col-sm-6 col-lg-12">
              <h2>Latest store items</h2>
              <div class="well">
              <div row>
                <div class="col-6 col-sm-6 col-lg-2"><img src="/gfx/store/98_01.jpg"></div>
                <div class="col-6 col-sm-6 col-lg-2"><img src="/gfx/store/99_01.jpg"></div>
                <div class="col-6 col-sm-6 col-lg-2"><img src="/gfx/store/100_01.jpg"></div>
                <div class="col-6 col-sm-6 col-lg-2"><img src="/gfx/store/101_01.jpg"></div>
                <div class="col-6 col-sm-6 col-lg-2"><img src="/gfx/store/102_01.jpg"></div>
                <div class="col-6 col-sm-6 col-lg-2"><img src="/gfx/store/103_01.jpg"></div>

              <p><a class="btn btn-default" href="#" role="button">Search store &raquo;</a></p>
              </div>  <!--/row-->
              </div>
            </div><!--/span-->


