<div class="col-4 col-sm-6 col-lg-12">
     <p><center><a class="btn btn-default" href="#" role="button">Submit a link &raquo;</a></center></p>
</div>
<h2>Official Sierra</h2>
<div class="well">
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://www.sierra.com" target="_blank"><img src="/gfx/links/sierra.jpg"></a>
          Official site of Sierra
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://www.activision.com" target="_blank"><img src="/gfx/links/activision.jpg"></a>
          Parent company of Sierra
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://www.futurlab.co.uk/" target="_blank"><img src="/gfx/links/Futurlab.jpg"></a>
          Developer of Velocity 2X
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://www.lucidgames.co.uk/" target="_blank"><img src="/gfx/links/lucid.jpg"></a>
          Developer of Geometry Wars 3: Dimensions
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://blog.theoddgentlemen.com/" target="_blank"><img src="/gfx/links/odd_gentlemen.jpg"></a>
          Developer of King's Quest 2015
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://www.rockpocketgames.com/" target="_blank"><img src="/gfx/links/Rockpocket.png"></a>
          Developer of Shiftlings
     </div>
</div>
</div>
<h2>Indie and alumn game developers</h2>
<div class="well">
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://www.agdinteractive.com/" target="_blank"><img src="/gfx/links/agd.png"></a>
          VGA remakes of classics
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://guysfromandromeda.com/" target="_blank"><img src="/gfx/links/andromeda.png"></a>
          Scott Murphy's and Mark Crowe's SpaceVenture
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://www.infamous-adventures.com/home/" target="_blank"><img src="/gfx/links/ia.png"></a>
          VGA remakes of classics
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://www.iracing.com/" target="_blank"><img src="/gfx/links/iRacing.png"></a>
          David Kaemmer race simulations
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://www.madottergames.com/" target="_blank"><img src="/gfx/links/madotter.png"></a>
          Mad Otter: Damon Slye's game studio
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://www.postudios.com/company/" target="_blank"><img src="/gfx/links/phoenix.png"></a>
          Gabriel Knight remake and more
     </div>
</div>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://pinkertonroad.com/" target="_blank"><img src="/gfx/links/pinkerton.JPG"></a>
          Jane Jensen and Robert Holmes studio
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://artbykjell.com/" target="_blank"><img src="/gfx/links/kjell.png"></a>
          Space Quest 3 3D, Rise of the Dragon 3D
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://www.boxofmystery.com/games/incinerations/" target="_blank"><img src="/gfx/links/incinerations.png"></a>
          Space Quest: Incinerations
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://spotkin.com/" target="_blank"><img src="/gfx/links/spotkin.png"></a>
          Jeff Tunnell's and Kevin Ryan's game studio
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://tiltedmill.com/" target="_blank"><img src="/gfx/links/tiltedmill.png"></a>
          Former Impressions team games
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://transolar.com/" target="_blank"><img src="/gfx/links/transolar.png"></a>
          Corey and Lori Cole's Hero-U
     </div>
</div>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://www.sqvsb.com/" target="_blank"><img src="/gfx/links/vsb.png"></a>
          Space Quest: Vohaul Strikes Back
     </div>
</div>
</div>
<h2>Sierra fan sites</h2>
<div class="well">
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://www.sierragamers.com" target="_blank"><img src="/gfx/links/SierraGamers.jpg"></a>
          Sierra site of Ken and Roberta Williams
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://www.sierrahelp.com" target="_blank"><img src="/gfx/links/sierrahelp.png"></a>
          Classic Sierra tech support and more
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://www.artofsierra.com/" target="_blank"><img src="/gfx/links/artofsierra.jpg"></a>
          Sierra art preservation project
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://www.sierramusiccentral.com/" target="_blank"><img src="/gfx/links/SMC.JPG"></a>
          Sierra Music Central
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://www.midimusicadventures.com/" target="_blank"><img src="/gfx/links/midimusic.png"></a>
          Classic Sierra music
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://larrylaffer.net/" target="_blank"><img src="/gfx/links/Larry.bmp"></a>
          Home of Leisure Suit Larry
     </div>
</div>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://www.spacequest.net/page/index.html" target="_blank"><img src="/gfx/links/sqn.png"></a>
          Space Quest series
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://wiw.org/~jess/roger2.html" target="_blank"><img src="/gfx/links/broomcloset.png"></a>
          Space Quest series
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://www.questformoreglory.com/index.html" target="_blank"><img src="/gfx/links/qfmg.png"></a>
          Quest for Glory series
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://www.sierraplanet.com/" target="_blank"><img src="/gfx/links/SierraPlanet.png"></a>
          Roberta Williams games
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://www.unityhq.net/" target="_blank"><img src="/gfx/links/unityhq.png"></a>
          Home of No One Lives Forever series
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://www.unityhq.net/" target="_blank"><img src="/gfx/links/saveEE.png"></a>
          Home of Empire Earth series
     </div>
</div>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://www.sierrawallpaper.com/" target="_blank"><img src="/gfx/links/wallpaper.png"></a>
          Fan-made classic Sierra wallpapers
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://www.peppersadventures.com/" target="_blank"><img src="/gfx/links/pepper.png"></a>
          Pepper's Adventures in Time
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="https://notendur.hi.is/~eybjorn/krondor/krondor.html" target="_blank"><img src="/gfx/links/krondor.png"></a>
          Betrayal at Krondor fan site
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="http://anthonylarme.tripod.com/phantas/" target="_blank"><img src="/gfx/links/phantas.png"></a>
          Phantasmagoria series fan site
     </div>
</div>
</div>
<h2>Other links</h2>
<div class="col-4 col-sm-6 col-lg-6">
<div class="well">
     <h2><small>Omnipedia</small></h2>
     <a href="http://gabrielknight.wikia.com/wiki/Gabriel_Knight_Omnipedia" target="_blank">Gabriel Knight Omnipedia</a><br>
     <a href="http://kingsquest.wikia.com/wiki/King's_Quest_Omnipedia" target="_blank">King's Quest Omnipedia</a><br>
     <a href="http://leisuresuitlarry.wikia.com/wiki/Leisure_Suit_Larry_Omnipedia" target="_blank">Leisure Suit Larry Omnipedia</a><br>
     <a href="http://policequest.wikia.com/wiki/Police_Quest_Omnipedia" target="_blank">Police Quest Omnipedia</a><br>
     <a href="http://questforglory.wikia.com/wiki/Quest_for_Glory_Omnipedia" target="_blank">Quest for Glory Omnipedia</a><br>
     <a href="http://spacequest.wikia.com/wiki/Space_Quest_Omnipedia" target="_blank">Space Quest Omnipedia</a><br>
     <h2><small>Crowdfunding projects</small></h2>
     <a href="https://www.kickstarter.com/projects/transolargames/hero-u-rogue-to-redemption" target="_blank">Hero-U: Rogue to Redemption</a><br>
     <a href="https://www.kickstarter.com/projects/transolargames/hero-u-adventure-role-playing-game" target="_blank">Hero-U: Rogue to Redemption (Kickstarter 2)</a><br>
     <a href="https://www.kickstarter.com/projects/leisuresuitlarry/make-leisure-suit-larry-come-again" target="_blank">Leisure Suit Larry Reloaded</a><br>
     <a href="https://www.kickstarter.com/projects/1005365109/jane-jensens-pinkerton-road-2012-2013-csg" target="_blank">Pinkerton Road</a><br>
     <a href="https://www.kickstarter.com/projects/precinctgame/precinct" target="_blank">Precinct</a><br>
     <a href="https://www.kickstarter.com/projects/madottergames/red-baron" target="_blank">Red Baron</a><br>
     <a href="https://www.kickstarter.com/projects/spaceventure/two-guys-spaceventure-by-the-creators-of-space-que" target="_blank">SpaceVenture</a><br>
     <a href="https://www.kickstarter.com/projects/mrkenallen/under-the-half-dome-an-album-by-sierra-composer-ke" target="_blank">Under the Half-Dome</a><br>
</div>
</div>
<div class="col-4 col-sm-6 col-lg-6">
<div class="well">
     <h2><small>Alums</small></h2>
     <a href="http://www.allowe.com/" target="_blank">Al Lowe's Humor Site</a><br>
     <a href="http://www.christymarx.com/" target="_blank">Christy Marx</a><br>
     <a href="http://www.markseibert.com/" target="_blank">Mark Seibert</a><br>
     <a href="http://www.jimwallsreloaded.com/" target="_blank">Jim Walls Reloaded</a><br>
</div>
</div>
