<div class="col-4 col-sm-6 col-lg-12">
     <p><center><a class="btn btn-default" href="#" role="button">Upload merchandise &raquo;</a></center></p>
</div>
<h2>Clothing</h2>
<div class="well">
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">3-D Animated Adventure T-shirt</a><br>
          <a href="#"><img src="/gfx/memor/3Dadventure_tshirt_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Colonel's Bequest T-shirt</a><br>
          <a href="#"><img src="/gfx/memor/LB1_tshirt_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">F.E.A.R. T-shirt</a><br><br>
          <a href="#"><img src="/gfx/memor/FEAR_tshirt_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Freddy Pharkas T-shirt (art)</a><br>
          <a href="#"><img src="/gfx/memor/FPFP_tshirt_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Hard Disk T-shirt</a><br><br>
          <a href="#"><img src="/gfx/memor/Harddisk_tshirt_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Hero's Quest sweater</a><br><br>
          <a href="#"><img src="/gfx/memor/QfG1_tshirt_icon.JPG"></a>
     </div>
</div>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Leisure Suit Larry 1 (EGA) T-shirt</a><br>
          <a href="#"><img src="/gfx/memor/LSL1_tshirt_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Lighthouse T-shirt</a><br><br>
          <a href="#"><img src="/gfx/memor/Lighthouse_shirt_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Lords of Magic T-shirt</a><br><br>
          <a href="#"><img src="/gfx/memor/LoM_tshirt_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Quest for Glory 5 T-shirt</a><br><br>
          <a href="#"><img src="/gfx/memor/qfg5_tshirt_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">SCI-32 T-shirt</a><br><br>
          <a href="#"><img src="/gfx/memor/SCI32_tshirt_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra 10th Anniversary tour jacket</a><br>
          <a href="#"><img src="/gfx/memor/jacket_icon.JPG"></a>
     </div>
</div>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra 10 Years Employee jacket</a><br>
          <a href="#"><img src="/gfx/memor/jacket_10year_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra 5 Years Employee sweater</a><br>
          <a href="#"><img src="/gfx/memor/sweater_5year_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra FX shirt</a><br><br>
          <a href="#"><img src="/gfx/memor/sierraFX_shirt_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra T-shirt</a><br><br>
          <a href="#"><img src="/gfx/memor/sierra_tshirt_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Shivers T-shirt</a><br><br>
          <a href="#"><img src="/gfx/memor/shivers_tshirt_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">SWAT 2 caps</a><br><br>
          <a href="#"><img src="/gfx/memor/swat2_caps_icon.JPG"></a>
     </div>
</div>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">SWAT 2 T-shirt</a><br><br>
          <a href="#"><img src="/gfx/memor/swat2_tshirt_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Yosemite Entertainment T-shirt</a><br>
          <a href="#"><img src="/gfx/memor/entertaiment_back_icon.JPG"></a>
     </div>
</div>
</div>
<h2>Mouse pads</h2>
<div class="well">
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">How to Pick Up Clicks mousepad</a><br>
          <a href="#"><img src="/gfx/memor/LSL_mousepad_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra Originals mouse pad</a><br>
          <a href="#"><img src="/gfx/memor/Sierra_mousepad_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Babylon 5 mouse pad</a><br><br>
          <a href="#"><img src="/gfx/memor/Babylon5_mousepad_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Imagination - The Sierra Network mouse pad</a><br>
          <a href="#"><img src="/gfx/memor/TSN_mousepad_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Best of Sierra mouse pad</a><br>
          <a href="#"><img src="/gfx/memor/best_of_sierra_mousepad_icon.JPG"></a>
     </div>
</div>
</div>
<h2>Mugs</h2>
<div class="well">
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra Japan mug</a><br><br>
          <a href="#"><img src="/gfx/memor/japan_mug_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Dynamix mug</a><br><br>
          <a href="#"><img src="/gfx/memor/dynamix_mug_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">My Life Needs A Save Game Feature mug</a><br>
          <a href="#"><img src="/gfx/memor/savegame_mug_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Quest for Glory V: Dragon Fire mug</a><br>
          <a href="#"><img src="/gfx/memor/QFG5_mug_icon.jpg"></a>
     </div>
</div>
</div>
<h2>Pins / patches</h2>
<div class="well">
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">King's Quest VI pin</a><br><br>
          <a href="#"><img src="/gfx/memor/KQ6_pin_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">King's Quest 2015 pin</a><br><br>
          <a href="#"><img src="/gfx/memor/KQ9_pin_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Outpost patch</a><br><br>
          <a href="#"><img src="/gfx/memor/outpost_patch_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Quest for Glory 5 pin</a><br><br>
          <a href="#"><img src="/gfx/memor/QfG5_pin_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Roger Wilco patch</a><br><br>
          <a href="#"><img src="/gfx/memor/rogerwilco_patch_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra 10th Anniversary Tour Guest Pass</a><br>
          <a href="#"><img src="/gfx/memor/iron_on_patch_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra patches</a><br><br>
          <a href="#"><img src="/gfx/memor/oldandolder_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Space Quest 3 pin</a><br><br>
          <a href="#"><img src="/gfx/memor/SQ3_pin_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">We Play Games With Your Mind! pin</a><br>
          <a href="#"><img src="/gfx/memor/mind_pin_icon.JPG"></a>
     </div>
</div>
</div>
<h2>Posters</h2>
<div class="well">
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">A-10 Tank Killer poster</a><br><br>
          <a href="#"><img src="/gfx/memor/A10_poster_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Aces of the Pacific Poster</a><br>
          <a href="#"><img src="/gfx/memor/AcesPacific_poster_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Babylon 5 Poster</a><br><br>
          <a href="#"><img src="/gfx/memor/babylon5_poster_icon.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Caesar IV poster</a><br><br>
          <a href="#"><img src="/gfx/memor/Caesar4_poster_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Codename: Iceman centerfold</a><br>
          <a href="#"><img src="/gfx/memor/iceman_poster_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Conquests of Camelot poster</a><br>
          <a href="#"><img src="/gfx/memor/conquests1_poster_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Counter Strike: Condition Zero poster</a><br>
          <a href="#"><img src="/gfx/memor/CS_CZ_poster_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Gabriel Knight 3 poster</a><br><br>
          <a href="#"><img src="/gfx/memor/GK3_poster_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Gold Rush poster</a><br><br>
          <a href="#"><img src="/gfx/memor/goldrush_poster_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Joint Task Force poster</a><br><br>
          <a href="#"><img src="/gfx/memor/JTF_poster_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">King's Quest VII poster</a><br><br>
          <a href="#"><img src="/gfx/memor/KQ7_poster_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Lost Mind of Dr. Brain poster</a><br>
          <a href="#"><img src="/gfx/memor/Brain3_poster_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Malice poster</a><br><br>
          <a href="#"><img src="/gfx/memor/Malice_poster_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Manhunter 2 centerfold</a><br><br>
          <a href="#"><img src="/gfx/memor/manhunter2_poster_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Navy Seals poster</a><br><br>
          <a href="#"><img src="/gfx/memor/navyseals_poster_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Navy Seals poster</a><br><br>
          <a href="#"><img src="/gfx/memor/navyseals_poster2_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Phantasmagoria poster</a><br><br>
          <a href="#"><img src="/gfx/memor/PH1_poster_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Police Quest 2 centerfold</a><br>
          <a href="#"><img src="/gfx/memor/PQ2_poster_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Return of the Lounge Lizard King centerfold</a><br>
          <a href="#"><img src="/gfx/memor/LSL_interaction_poster_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Rise of the Dragon centerfold</a><br>
          <a href="#"><img src="/gfx/memor/RiseDragon_poster_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra Discovery Series poster</a><br>
          <a href="#"><img src="/gfx/memor/discovery_poster_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Silpheed poster</a><br><br>
          <a href="#"><img src="/gfx/memor/silpheed_poster_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Slater - King's Quest V centerfold</a><br>
          <a href="#"><img src="/gfx/memor/SlaterKQ5_poster_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">SWAT 2 poster</a><br><br>
          <a href="#"><img src="/gfx/memor/swat2_poster_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Thexder poster</a><br><br>
          <a href="#"><img src="/gfx/memor/Thexder_poster_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Thexder (for Windows 95) poster</a><br>
          <a href="#"><img src="/gfx/memor/thexder95_poster_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Timeshift poster</a><br><br>
          <a href="#"><img src="/gfx/memor/Timeshift_poster_icon.JPG"></a>
     </div>
</div>
</div>
<h2>Miscellaneous</h2>
<div class="well">
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Apple Cider Spider Cider</a><br><br>
          <a href="#"><img src="/gfx/memor/SpiderCider_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Babylon 5 watch</a><br><br>
          <a href="#"><img src="/gfx/memor/Babylon5_watch_icon.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Babylon 5 fridge magnet</a><br><br>
          <a href="#"><img src="/gfx/memor/babylon5_magnet_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Blizzard Entertainment notepad</a><br>
          <a href="#"><img src="/gfx/memor/blizzard_notepad_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Conquests of Camelot statuette</a><br>
          <a href="#"><img src="/gfx/memor/Conquests1_statuette_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Empire Earth Globe</a><br><br>
          <a href="#"><img src="/gfx/memor/EE_globe1_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Front Page Sports Football bag</a><br>
          <a href="#"><img src="/gfx/memor/football_bag_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">King's Quest VI Lithograph</a><br>
          <a href="#"><img src="/gfx/memor/KQ6_lithograph_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Leisure Suit Larry 2 towel</a><br>
          <a href="#"><img src="/gfx/memor/LSL2_towel_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Phantasmagoria towel</a><br><br>
          <a href="#"><img src="/gfx/memor/PH1_towel_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Shadow of Yserbius award</a><br>
          <a href="#"><img src="/gfx/memor/yserbiusaward_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra Employee Handbook</a><br>
          <a href="#"><img src="/gfx/memor/employeehandbook_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra FX notepad</a><br><br>
          <a href="#"><img src="/gfx/memor/sierraFX_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra On-Line wine</a><br><br>
          <a href="#"><img src="/gfx/memor/wine_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Space Quest V Spike doll</a><br>
          <a href="#"><img src="/gfx/memor/SQ5_spikedoll_icon.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Throne of Darkness figurines</a><br>
          <a href="#"><img src="/gfx/memor/throne_figurine_icon.JPG"></a>
     </div>

</div>
</div>
