<div class="col-4 col-sm-6 col-lg-12">
     <p><center><a class="btn btn-default" href="#" role="button">Upload Sierra magazine scans &raquo;</a></center></p>
</div>
<h2>On-Line Systems</h2>
<div class="well">
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">The On-Line Letter, Volume 1, Number 1</a><br>
          <a href="#"><img src="/gfx/Publications/IA/Online01/01.JPG"></a>
     </div>
</div>
</div>
<h2>Sierra Newsletter (1987 - 1989)</h2>
<div class="well">
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra Newsletter Volume 1 Number 2 (late 1987)</a><br>
          <a href="#"><img src="/gfx/Publications/IA/Newsletter_1_2/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra Newsletter Volume 1 Number 3: Spring 1988</a><br>
          <a href="#"><img src="/gfx/Publications/IA/Newsletter_1_3/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra Newsletter Volume 1 Number 4: Winter 1988</a><br>
          <a href="#"><img src="/gfx/Publications/IA/Newsletter_1_4/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra Newsletter Volume 2 Number 1: Spring 1989</a><br>
          <a href="#"><img src="/gfx/Publications/IA/Newsletter_2_1/01.JPG"></a>
     </div>
</div>
</div>
<h2>Sierra News Magazine (1989 - 1991)</h2>
<div class="well">
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra News Magazine Volume 2 Number 2: Autumn 1989</a><br>
          <a href="#"><img src="/gfx/Publications/IA/Newsmagazine_2_2/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra News Magazine Volume 3 Number 1: Spring 1990</a><br>
          <a href="#"><img src="/gfx/Publications/IA/Newsmagazine_3_1/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra News Magazine Volume 3 Number 2: Summer 1990</a><br>
          <a href="#"><img src="/gfx/Publications/IA/Newsmagazine_3_2/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra News Magazine Volume 3 Number 3: Fall 1990</a><br>
          <a href="#"><img src="/gfx/Publications/IA/Newsmagazine_3_3/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra News Magazine Volume 4 Number 1: Spring 1991</a><br>
          <a href="#"><img src="/gfx/Publications/IA/Newsmagazine_4_1/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Sierra News Magazine Volume 4 Number 2: Summer 1991</a><br>
          <a href="#"><img src="/gfx/Publications/IA/Newsmagazine_4_2/01.JPG"></a>
     </div>
</div>
</div>
<h2>InterAction (1991 - 1999)</h2>
<div class="well">
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 4 Number 3: Fall 1991</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_4_3/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 5 Number 1: Spring 1992</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_5_1/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 5 Number 2: Summer 1992</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_5_2/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 5 Number 3: Fall 1992</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_5_3/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 5 Number 4: Winter 1992</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_5_4/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 6 Number 1: June 1993</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_6_1/01.JPG"></a>
     </div>
</div>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 6 Number 2: Summer 1993</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_6_2/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 6 Number 3: Holiday 1993</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_6_3/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 6 Number 4: Spring 1994</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_6_4/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 7 Number 1: Fall 1994</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_7_1/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 7 Number 2: Holiday 1994</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_7_2/01.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 8 Number 1: Spring 1995</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_8_1/001.jpg"></a>
     </div>
</div>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 8 Number 2: Fall 1995</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_8_2/001.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 8 Number 3: Holiday 1995</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_8_3/001.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 9 Number 1: Spring 1996</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_9_1/001.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 9 Number 2: Summer 1996</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_9_2/001.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 9 Number 3: Fall 1996</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_9_3/001.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 9 Number 4: Holiday 1996</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_9_4/001.jpg"></a>
     </div>
</div>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 10 Number 1: Spring 1997</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_10_1/001.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 10 Number 2: Summer 1997</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_10_2/001.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 10 Number 3: Fall 1997</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_10_3/001.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 10 Number 4: Holiday 1997</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_10_4/001.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 11 Number 1: Spring 1998</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_11_1/001.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 11 Number 2: Summer 1998</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_11_2/001.JPG"></a>
     </div>
</div>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 11 Number 3: Fall 1998</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_11_3/001.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 11 Number 4: Holiday 1998</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_11_4/001.JPG"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">InterAction Volume 12 Number 1: Spring 1999</a><br>
          <a href="#"><img src="/gfx/Publications/IA/IA_12_1/001.JPG"></a>
     </div>
</div>
</div>
<h2>Best of Sierra (German)</h2>
<div class="well">
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Best of Sierra 1: 6-7 1997</a><br>
          <a href="#"><img src="/gfx/Publications/Best_of_Sierra/Best_of_Sierra_1/01.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Best of Sierra 2: Sept.+Okt.1997</a><br>
          <a href="#"><img src="/gfx/Publications/Best_of_Sierra/Best_of_Sierra_2/01.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Best of Sierra 3: Nov.+Dez.1997</a><br>
          <a href="#"><img src="/gfx/Publications/Best_of_Sierra/Best_of_Sierra_3/01.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Best of Sierra 4: Jan.+Feb.1998</a><br>
          <a href="#"><img src="/gfx/Publications/Best_of_Sierra/Best_of_Sierra_4/01.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Best of Sierra 5: Mar.+Apr.1998</a><br>
          <a href="#"><img src="/gfx/Publications/Best_of_Sierra/Best_of_Sierra_5/01.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Best of Sierra 6: Mai+Jun.1998</a><br>
          <a href="#"><img src="/gfx/Publications/Best_of_Sierra/Best_of_Sierra_6/01.jpg"></a>
     </div>
</div>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Best of Sierra 7: Jul.+Aug. 1998</a><br>
          <a href="#"><img src="/gfx/Publications/Best_of_Sierra/Best_of_Sierra_7/01.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Best of Sierra 8: Sept.+Okt.1998</a><br>
          <a href="#"><img src="/gfx/Publications/Best_of_Sierra/Best_of_Sierra_8/01.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Best of Sierra 9: Nov.+Dez.1998</a><br>
          <a href="#"><img src="/gfx/Publications/Best_of_Sierra/Best_of_Sierra_9/01.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Best of Sierra 10: Jan.+Feb.1999</a><br>
          <a href="#"><img src="/gfx/Publications/Best_of_Sierra/Best_of_Sierra_10/01.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Best of Sierra 11: Mar.+Apr.1999</a><br>
          <a href="#"><img src="/gfx/Publications/Best_of_Sierra/Best_of_Sierra_11/01.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Best of Sierra 12: Mai+Jun.1999</a><br>
          <a href="#"><img src="/gfx/Publications/Best_of_Sierra/Best_of_Sierra_12/01.jpg"></a>
     </div>
</div>
<div class="row">
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Best of Sierra 13: Jul.+Aug. 1999</a><br>
          <a href="#"><img src="/gfx/Publications/Best_of_Sierra/Best_of_Sierra_13/01.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Best of Sierra 14: Sept.+Okt.1999</a><br>
          <a href="#"><img src="/gfx/Publications/Best_of_Sierra/Best_of_Sierra_14/01.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Best of Sierra 15: Nov.+Dez.1999</a><br>
          <a href="#"><img src="/gfx/Publications/Best_of_Sierra/Best_of_Sierra_15/01.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Best of Sierra 16: Jan.+Feb.2000</a><br>
          <a href="#"><img src="/gfx/Publications/Best_of_Sierra/Best_of_Sierra_16/01.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Best of Sierra 17: Mar.+Apr.2000</a><br>
          <a href="#"><img src="/gfx/Publications/Best_of_Sierra/Best_of_Sierra_17/01.jpg"></a>
     </div>
     <div class="col-4 col-sm-6 col-lg-2">
          <a href="#">Best of Sierra 18: Mai+Jun.2000</a><br>
          <a href="#"><img src="/gfx/Publications/Best_of_Sierra/Best_of_Sierra_18/01.jpg"></a>
     </div>
</div>
</div>
