<!DOCTYPE html>
<!--[if lt IE 7]>   <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>      <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>      <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <title>The Sierra Chest - Sierrachest.com</title>
        <meta name="description" content="">
        <!-- Mobile Devices Viewport Resset-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <link rel="icon" type="image/png" href="img/favicon.png">
        <link rel="stylesheet" href="/vendor/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="/vendor/font-awesome/css/font-awesome.min.css">
        <!--[if IE 8]>
            <link rel="stylesheet" href="/vendor/font-awesome/css/font-awesome-ie7.min.css">
        <![endif]-->
        <link rel="stylesheet" href="/vendor/prettyPhoto/css/prettyPhoto.css">
        <link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700|Lato:300,400,700,400italic,700italic|Droid+Serif' rel='stylesheet' type='text/css'>
        <!-- base layout styling -->
        <link rel="stylesheet" href="/css/base.css">
        <!-- components styling -->
        <link rel="stylesheet" href="/css/components.css">
        <!-- template colorschemes -->
        <link rel="stylesheet" href="/css/default.css">
        <script src="/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
        <?= $this->headLink() ?>
    </head>
    <body>
        <h1 class="sr-only">Sierra Chest</h1>
        <?= $this->partial('partials/header.phtml', 'default'); ?>
        <?= $this->layout()->content; ?>
        <?= $this->partial('partials/footer.phtml', 'default'); ?>

        <script src="/vendor/jquery-1.10.1.min.js"></script>
        <!--
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="/vendor/jquery-1.10.1.min.js"><\/script>')</script>
        -->
        <script src="/vendor/bootstrap/js/bootstrap.min.js"></script>
        <script src="/vendor/prettyPhoto/jquery.prettyPhoto.js"></script>

        <script src="/vendor/jquery.unveil.min.js"></script>
        <script src="/js/main.js"></script>
        <script src="/js/sierra.js" type="text/javascript"></script>
        <?= $this->headScript() ?>
    </body>
</html>
