<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="shortcut icon" type="image/png" href="/img/favicon.png">

        <title>The Sierra Chest</title>

        <!-- Bootstrap core CSS -->
        <link href="/css/bootstrap.min.css" rel="stylesheet">
        <link href="/css/site.css" rel="stylesheet">
        <?= $this->headLink() ?>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <?= $this->partial('partials/header.phtml', 'default'); ?>

        <div class="container">
            <div class="row row-offcanvas row-offcanvas-right">
                <div class="col-xs-16 col-sm-12">
                    <p class="pull-right visible-xs">
                        <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
                    </p>
                    <?= $this->layout()->content; ?>
                    <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
                         <!--<?= $this->partial('partials/menu.phtml', 'default'); ?>-->
                    </div>

                </div>
                <hr>
                <footer>
                    <p><a href="https://www.youtube.com/user/ruudje1976" target="_blank"><img src="gfx/general/youtube.JPG"></a>
                    <a href="https://www.facebook.com/groups/172140776253988/" target="_blank"><img src="gfx/general/facebook.JPG"></a>
                    <a href="https://twitter.com/SierraChest" target="_blank"><img src="gfx/general/twitter.JPG"></a></p>
                    <br><center><p>&copy; The Sierra Chest 2008 - <?= date('Y') ?></p></center>
                </footer>
            </div>

        </div>
        <script src="/js/library/jquery-1.10.2.min.js" type="text/javascript"></script>
        <script src="/js/library/bootstrap.min.js" type="text/javascript"></script>
        <script src="/js/sierra.js" type="text/javascript"></script>
        <?= $this->headScript() ?>
</body>
</html>
