<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Sierra Chest</a>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="Dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Media <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">News blog</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Publications</li>
                    <li><a href="#">Sierra Magazines</a></li>
                    <li><a href="#">Sierra Catalogues</a></li>
                    <li><a href="#">Sierra Buyer's Guides</a></li>
                    <li><a href="#">TSN Times</a></li>
                    <li><a href="#">Video ads</a></li>
                    <li><a href="#">Other media</a></li>
                  </ul>
                </li>
                <li class="Dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Games <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Search games</a></li>
                    <li><a href="#">Music</a></li>
                    <li><a href="#">Cheats</a></li>
                    <li><a href="#">Easter Eggs</a></li>
                    <li><a href="#">Maps</a></li>
                    <li><a href="#">Packaging and content</a></li>
                    <li><a href="#">Downloads</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Extras</li>
                    <li><a href="#">Demos & trailers</a></li>
                    <li><a href="#">Hint books & strategy guides</a></li>
                    <li><a href="#">Books</a></li>
                    <li><a href="#">Merchandise</a></li>
                  </ul>
                </li>
                <li class="Dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Community <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">My profile</a></li>
                    <li><a href="#">My contributions</a></li>
                    <li><a href="#">My collection</a></li>
                    <li><a href="#">Notifications</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Members</a></li>
                    <li><a href="#">Collector's Corner</a></li>
                    <li><a href="#">Forums</a></li>
                  </ul>
                </li>
                <li class="Dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Store <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li class="dropdown-header">Buyers </li>
                    <li><a href="#">Search items</a></li>
                    <li><a href="#">All stores</a></li>
                    <li><a href="#">My wishlist</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Sellers </li>
                    <li><a href="#">Create/edit store</a></li>
                    <li><a href="#">Manage listings</a></li>
                    <li><a href="#">Most wanted</a></li>
                  </ul>
                </li>
                <li class="Dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Development <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Developers/publishers</a></li>
                    <li><a href="#">People</a></li>
                    <li><a href="#">Platforms</a></li>
                    <li><a href="#">Engines</a></li>
                    </ul>
                </li>
                <li class="Dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">The Chest <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">About us</a></li>
                    <li><a href="#">Our supporters</a></li>
                    <li><a href="#">Become a Patron</a></li>
                    <li><a href="#">Links</a></li>
                    <li><a href="#">Guestbook</a></li>
                  </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-right" role="form">
                <div class="form-group">
                    <input type="text" placeholder="Search for a game" class="form-control">
                </div>
            </form>
        </div>
    </div>
</div>
