<nav id="header" class="header-navbar" role="navigation">
    <div class="header-navbar-inner container">
        <div id="brand" class="navbar-brand">
            <a href="index.html" rel="bookmark">
                <!-- to disable lazy loading, remove data-src and data-src-retina -->
                <img src="/img/logo.png" data-src="/img/logo.png" data-src-retina="/img/logo-retina.png" width="244" height="56" alt="">
                <!--fallback for no javascript browsers-->
                <noscript>
                    <img src="/img/logo.png" alt="">
                </noscript>
            </a>
        </div>
        <ul class="nav nav-pages hidden-xs">
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
            <li><a href="#">Advertise </a></li>
            <li><a href="#">Terms &amp; Conditions</a></li>
            <li><a href="#">Privacy</a></li>
        </ul>
        <ul class="nav nav-icons">
            <li>
                <a href="#" class="btn-icon" data-toggle=".header-navbar-inner" data-toggle-class="search-toggled-in">
                    <span class="search-toggled-out-icon glyphicon glyphicon-search"></span>
                    <span class="search-toggled-in-icon glyphicon glyphicon-remove"></span>
                </a>
            </li>
        </ul>
        <div class="search-wrapper js-stoppropagation">
            <div class="search-wrapper-inner">
                <form>
                    <input type="text" value="" placeholder="search ... ">
                    <button class="btn-icon" type="submit"><span class="glyphicon glyphicon-search"></span></button>
                </form>
            </div>
        </div>
        <ul class="nav navbar-nav">
            <li class="nav-all pull-right full-subnav-wrapper">
                <a href="#" data-toggle="li">
                    <span class="text">All Categories</span>
                    <span class="toggle glyphicon glyphicon-align-justify"></span>
                </a>
                <div class="row subnav-wrapper">
                    <div class="col-md-2 col-sm-2 bg-bar">
                        <strong class="subnav-header">Pages</strong>
                        <ul class="subnav-full">
                            <li><a href="index.html">Blog 3 Columns</a></li>
                            <li><a href="blog.html">Blog 2 Columns</a></li>
                            <li><a href="blog-grids.html">Blog Grids</a></li>
                            <li><a href="reviews.html">Reviews Archive</a></li>
                            <li><a href="single.html">Single Blog</a></li>
                            <li><a href="single-full.html">Single Blog (Full)</a></li>
                            <li><a href="components.html">Components</a></li>
                        </ul>
                    </div>
                    <div class="col-md-2 col-sm-2">
                        <strong class="subnav-header">Colorschemes</strong>
                        <ul class="subnav-full">
                            <li><a href="/html/">Coolorize</a></li>
                            <li><a href="/html-dark/">Dark</a></li>
                            <li><a href="/html-light/">Light</a></li>
                            <li><a href="#">Amet Commodo</a></li>
                            <li><a href="#">Consectetur </a></li>
                            <li><a href="#">Adipisicing</a></li>
                            <li><a href="#">Duis aute </a></li>
                        </ul>
                    </div>
                    <div class="col-md-2 col-sm-2">
                        <strong class="subnav-header">Banner Placements</strong>
                        <ul class="subnav-full">
                            <li><a href="banner-index.html">Home</a></li>
                            <li><a href="banner-single.html">Single</a></li>
                            <li><a href="#">Ipsum  Nisi </a></li>
                            <li><a href="#">Dolor Aliquip</a></li>
                        </ul>
                    </div>
                    <div class="col-md-2 col-sm-2">
                        <strong class="subnav-header">Category</strong>
                        <ul class="subnav-full">
                            <li><a href="#">Ipsum  Nisi </a></li>
                            <li><a href="#">Dolor Aliquip</a></li>
                            <li><a href="#">Amet Commodo</a></li>
                            <li><a href="#">Consectetur </a></li>
                        </ul>
                    </div>
                    <div class="col-md-2 col-sm-2">
                        <strong class="subnav-header">Category</strong>
                        <ul class="subnav-full">
                            <li><a href="#">Consectetur </a></li>
                            <li><a href="#">Adipisicing</a></li>
                            <li><a href="#">Ipsum  Nisi </a></li>
                            <li><a href="#">Dolor Aliquip</a></li>
                        </ul>
                    </div>
                    <div class="col-md-2 col-sm-2">
                        <strong class="subnav-header">Category</strong>
                        <ul class="subnav-full">
                            <li><a href="#">Ipsum  Nisi </a></li>
                            <li><a href="#">Dolor Aliquip</a></li>
                            <li><a href="#">Amet Commodo</a></li>
                            <li><a href="#">Consectetur </a></li>
                        </ul>
                    </div>
                </div>
            </li>
            <li class="active">
                <a href="#" data-toggle="li">Features</a>
                <div class="subnav-wrapper">
                    <ul class="subnav">
                        <li class="active"><a href="index.html">Blog 3 Columns</a></li>
                        <li><a href="blog.html">Blog 2 Columns</a></li>
                        <li><a href="blog-grids.html">Blog Grids</a></li>
                        <li><a href="reviews.html">Reviews Archive</a></li>
                        <li><a href="single.html">Single Blog</a></li>
                        <li><a href="single-full.html">Single Blog (Full)</a></li>
                        <li><a href="components.html">Components</a></li>
                        <li>
                            <a href="#" data-toggle="li">Colorshemes</a>
                            <div class="subnav-wrapper">
                                <ul class="subnav">
                                    <li><a href="/html/">Coolorize</a></li>
                                    <li><a href="/html-dark/">Dark</a></li>
                                    <li><a href="/html-light/">Light</a></li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a href="#" data-toggle="li">Banner Placements</a>
                            <div class="subnav-wrapper">
                                <ul class="subnav">
                                    <li><a href="banner-index.html">Home</a></li>
                                    <li><a href="banner-single.html">Single</a></li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="full-subnav-wrapper">
                <a href="#" data-toggle="li">Drop Down 2</a>
                <div class="row subnav-wrapper subnav-tabbed">
                    <ul class="col-md-2 col-sm-2 subnav-tabbed-tabs alignright">
                        <li class="active"><a href="#tabAll">All </a></li>
                        <li><a href="#tabNotebook">Notebook</a></li>
                        <li><a href="#tabSmartphone">Smartphone</a></li>
                    </ul>
                    <div class="col-md-10 col-sm-10 subnav-tabbed-panels">
                        <div id="tabAll" class="subnav-tabbed-panel active">
                            <article class="entry type-post style-thumbnail col-sm-3 col-md-3">
                                <figure class="entry-thumbnail">
                                    <a href="single.html">
                                            <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                        <img src="/img/placeholder.gif" data-src="http://placehold.it/230x230" data-src-retina="http://placehold.it/460x460" width="230" height="230" alt="">
                                        <!--fallback for no javascript browsers-->
                                        <noscript>
                                            <img src="http://placehold.it/230x230" alt="">
                                        </noscript>
                                    </a>
                                </figure>
                                <h3 class="entry-title"><a href="single.html">Sed ut perspiciatis unde omnis iste natus error sit voluptatem.</a> </h3>
                            </article>
                            <article class="entry type-post style-thumbnail col-sm-3 col-md-3">
                                <figure class="entry-thumbnail">
                                    <a href="single.html">
                                        <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                        <img src="/img/placeholder.gif" data-src="http://placehold.it/230x230" data-src-retina="http://placehold.it/460x460" width="230" height="230" alt="">
                                        <!--fallback for no javascript browsers-->
                                        <noscript>
                                            <img src="http://placehold.it/230x230" alt="">
                                        </noscript>
                                    </a>
                                </figure>
                                <h3 class="entry-title"><a href="single.html">Sed ut perspiciatis unde omnis iste natus error sit voluptatem.</a> </h3>
                            </article>
                            <article class="entry type-post style-thumbnail col-sm-3 col-md-3">
                                <figure class="entry-thumbnail">
                                    <a href="single.html">
                                        <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                        <img src="/img/placeholder.gif" data-src="http://placehold.it/230x230" data-src-retina="http://placehold.it/460x460" width="230" height="230" alt="">
                                        <!--fallback for no javascript browsers-->
                                        <noscript>
                                            <img src="http://placehold.it/230x230" alt="">
                                        </noscript>
                                    </a>
                                </figure>
                                <h3 class="entry-title"><a href="single.html">Sed ut perspiciatis unde omnis iste natus error sit voluptatem.</a> </h3>
                            </article>
                            <article class="entry type-post style-thumbnail col-sm-3 col-md-3">
                                <figure class="entry-thumbnail">
                                    <a href="single.html">
                                        <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                        <img src="/img/placeholder.gif" data-src="http://placehold.it/230x230" data-src-retina="http://placehold.it/460x460" width="230" height="230" alt="">
                                        <!--fallback for no javascript browsers-->
                                        <noscript>
                                            <img src="http://placehold.it/230x230" alt="">
                                        </noscript>
                                    </a>
                                </figure>
                                <h3 class="entry-title"><a href="single.html">Sed ut perspiciatis unde omnis iste natus error sit voluptatem.</a> </h3>
                            </article>
                        </div>
                        <div id="tabNotebook" class="subnav-tabbed-panel">
                            <article class="entry type-post style-thumbnail col-sm-3 col-md-3">
                                <figure class="entry-thumbnail">
                                    <a href="single.html">
                                        <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                        <img src="/img/placeholder.gif" data-src="http://placehold.it/230x230" data-src-retina="http://placehold.it/460x460" width="230" height="230" alt="">
                                        <!--fallback for no javascript browsers-->
                                        <noscript>
                                            <img src="http://placehold.it/230x230" alt="">
                                        </noscript>
                                    </a>
                                </figure>
                                <h3 class="entry-title"><a href="single.html">Sed ut perspiciatis unde omnis iste natus error sit voluptatem.</a> </h3>
                            </article>
                            <article class="entry type-post style-thumbnail col-sm-3 col-md-3">
                                <figure class="entry-thumbnail">
                                    <a href="single.html">
                                        <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                        <img src="/img/placeholder.gif" data-src="http://placehold.it/230x230" data-src-retina="http://placehold.it/460x460" width="230" height="230" alt="">
                                        <!--fallback for no javascript browsers-->
                                        <noscript>
                                            <img src="http://placehold.it/230x230" alt="">
                                        </noscript>
                                    </a>
                                </figure>
                                <h3 class="entry-title"><a href="single.html">Sed ut perspiciatis unde omnis iste natus error sit voluptatem.</a> </h3>

                            </article>
                            <article class="entry type-post style-thumbnail col-sm-3 col-md-3">
                                <figure class="entry-thumbnail">
                                    <a href="single.html">
                                        <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                        <img src="/img/placeholder.gif" data-src="http://placehold.it/230x230" data-src-retina="http://placehold.it/460x460" width="230" height="230" alt="">
                                        <!--fallback for no javascript browsers-->
                                        <noscript>
                                            <img src="http://placehold.it/230x230" alt="">
                                        </noscript>
                                    </a>
                                </figure>
                                <h3 class="entry-title"><a href="single.html">Sed ut perspiciatis unde omnis iste natus error sit voluptatem.</a> </h3>
                            </article>
                            <article class="entry type-post style-thumbnail col-sm-3 col-md-3">
                                <figure class="entry-thumbnail">
                                    <a href="single.html">
                                        <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                        <img src="/img/placeholder.gif" data-src="http://placehold.it/230x230" data-src-retina="http://placehold.it/460x460" width="230" height="230" alt="">
                                        <!--fallback for no javascript browsers-->
                                        <noscript>
                                            <img src="http://placehold.it/230x230" alt="">
                                        </noscript>
                                    </a>
                                </figure>
                                <h3 class="entry-title"><a href="single.html">Sed ut perspiciatis unde omnis iste natus error sit voluptatem.</a> </h3>

                            </article>
                        </div>
                        <div id="tabSmartphone" class="subnav-tabbed-panel">
                            <article class="entry type-post style-thumbnail col-sm-3 col-md-3">
                                <figure class="entry-thumbnail">
                                    <a href="single.html">
                                        <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                        <img src="/img/placeholder.gif" data-src="http://placehold.it/230x230" data-src-retina="http://placehold.it/460x460" width="230" height="230" alt="">
                                        <!--fallback for no javascript browsers-->
                                        <noscript>
                                            <img src="http://placehold.it/230x230" alt="">
                                        </noscript>
                                    </a>
                                </figure>
                                <h3 class="entry-title"><a href="single.html">Sed ut perspiciatis unde omnis iste natus error sit voluptatem.</a> </h3>
                            </article>
                            <article class="entry type-post style-thumbnail col-sm-3 col-md-3">
                                <figure class="entry-thumbnail">
                                    <a href="single.html">
                                        <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                        <img src="/img/placeholder.gif" data-src="http://placehold.it/230x230" data-src-retina="http://placehold.it/460x460" width="230" height="230" alt="">
                                        <!--fallback for no javascript browsers-->
                                        <noscript>
                                            <img src="http://placehold.it/230x230" alt="">
                                        </noscript>
                                    </a>
                                </figure>
                                <h3 class="entry-title"><a href="single.html">Sed ut perspiciatis unde omnis iste natus error sit voluptatem.</a> </h3>
                            </article>
                            <article class="entry type-post style-thumbnail col-sm-3 col-md-3">
                                <figure class="entry-thumbnail">
                                    <a href="single.html">
                                        <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                        <img src="/img/placeholder.gif" data-src="http://placehold.it/230x230" data-src-retina="http://placehold.it/460x460" width="230" height="230" alt="">
                                        <!--fallback for no javascript browsers-->
                                        <noscript>
                                            <img src="http://placehold.it/230x230" alt="">
                                        </noscript>
                                    </a>
                                </figure>
                                <h3 class="entry-title"><a href="single.html">Sed ut perspiciatis unde omnis iste natus error sit voluptatem.</a> </h3>
                            </article>
                            <article class="entry type-post style-thumbnail col-sm-3 col-md-3">
                                <figure class="entry-thumbnail">
                                    <a href="single.html">
                                        <!-- to disable lazy loading, remove data-src and data-src-retina -->
                                        <img src="/img/placeholder.gif" data-src="http://placehold.it/230x230" data-src-retina="http://placehold.it/460x460" width="230" height="230" alt="">
                                        <!--fallback for no javascript browsers-->
                                        <noscript>
                                            <img src="http://placehold.it/230x230" alt="">
                                        </noscript>
                                    </a>
                                </figure>
                                <h3 class="entry-title"><a href="single.html">Sed ut perspiciatis unde omnis iste natus error sit voluptatem.</a> </h3>
                            </article>
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <a href="#" data-toggle="li">Drop Down 3</a>
                <div class="subnav-wrapper">
                    <ul class="subnav-entries">
                        <li><a href="#">Recent Entry fits in this type of dropdown. </a></li>
                        <li><a href="#">Lorem ipsum dolor sit amet, consectetur adipisicing elit </a></li>
                        <li><a href="#">Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua </a></li>
                        <li><a href="#">Ut enim ad minim veniam, quis nostrud exercitation ullamco </a></li>
                        <li><a href="#">Laboris nisi ut aliquip ex ea commodo consequat. </a></li>
                        <li><a href="#">Duis aute irure dolor in reprehenderit</a></li>
                        <li><a href="#">In voluptate velit esse cillum dolore eu fugiat nulla pariatur</a></li>
                        <li><a href="#">Excepteur sint occaecat cupidatat non proident</a></li>
                        <li><a href="#">Sunt in culpa qui officia deserunt mollit anim id est laborum</a></li>
                    </ul>
                </div>
            </li>
            <li><a href="#">Category 1</a></li>
            <li><a href="#">Category 2</a></li>
            <li><a href="#">Category 3</a></li>
            <li><a href="#">Category 4</a></li>
            <li><a href="#">Category 5</a></li>
            <li><a href="#">Category 6</a></li>
            <li><a href="#">Category 7</a></li>
        </ul>
    </div>
</nav>



<!---
<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Sierra Chest</a>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="Dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Media <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">News blog</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Publications</li>
                    <li><a href="/index/sierra-magazines">Sierra Magazines</a></li>
                    <li><a href="/index/catalogs">Sierra Catalogues</a></li>
                    <li><a href="/index/buyers-guides">Sierra Buyer's Guides</a></li>
                    <li><a href="/index/tsn-times">TSN Times</a></li>
                    <li><a href="#">Video ads</a></li>
                    <li><a href="#">Other media</a></li>
                  </ul>
                </li>
                <li class="Dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Games <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="/index/game-search">Search games</a></li>
                    <li><a href="#">Music</a></li>
                    <li><a href="#">Cheats</a></li>
                    <li><a href="#">Easter Eggs</a></li>
                    <li><a href="#">Maps</a></li>
                    <li><a href="#">Packaging and content</a></li>
                    <li><a href="#">Downloads</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Extras</li>
                    <li><a href="/index/demos">Playable demos</a></li>
                    <li><a href="/index/trailers">Trailers / non-interactive demos</a></li>
                    <li><a href="#">Hint books & strategy guides</a></li>
                    <li><a href="/index/books">Books</a></li>
                    <li><a href="/index/merchandise">Merchandise</a></li>
                  </ul>
                </li>
                <li class="Dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Community <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">My profile</a></li>
                    <li><a href="#">My contributions</a></li>
                    <li><a href="#">My collection</a></li>
                    <li><a href="#">Notifications</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Members</a></li>
                    <li><a href="#">Collector's Corner</a></li>
                    <li><a href="#">Forums</a></li>
                  </ul>
                </li>
                <li class="Dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Store <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li class="dropdown-header">Buyers </li>
                    <li><a href="#">Search items</a></li>
                    <li><a href="#">All stores</a></li>
                    <li><a href="#">My wishlist</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Sellers </li>
                    <li><a href="#">Create/edit store</a></li>
                    <li><a href="#">Manage listings</a></li>
                    <li><a href="#">Most wanted</a></li>
                  </ul>
                </li>
                <li class="Dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Development <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Developers/publishers</a></li>
                    <li><a href="#">People</a></li>
                    <li><a href="#">Platforms</a></li>
                    <li><a href="#">Engines</a></li>
                    </ul>
                </li>
                <li class="Dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">The Chest <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="/index/about-us">About us</a></li>
                    <li><a href="#">Our supporters</a></li>
                    <li><a href="#">Become a Patron</a></li>
                    <li><a href="/index/links">Links</a></li>
                    <li><a href="#">Guestbook</a></li>
                  </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-right" role="form">
                <div class="form-group">
                    <input type="text" placeholder="Search for a game" class="form-control">
                </div>
            </form>
        </div>
    </div>
</div>
-->