<div class="list-group">
      <a href="#" class="list-group-item">Games</a>
      <a href="#" class="list-group-item">Blog</a>
      <a href="#" class="list-group-item">Forums</a>
      <a href="#" class="list-group-item">Store</a>
      <a href="#" class="list-group-item">People/Companies</a>
      <a href="#" class="list-group-item">Music Player</a>
      <a href="#" class="list-group-item">Memorabilia</a>
      <a href="#" class="list-group-item">Downloads</a>
</div>
